[loggers]
keys=root,CastoolsLibguestfs

[handlers]
keys=LogHandler

[formatters]
keys=LogFormatter

[logger_root]
level=DEBUG
handlers=LogHandler

[logger_CastoolsLibguestfs]
level=DEBUG
handlers=LogHandler
qualname=CastoolsLibguestfs
propagate=0

[handler_LogHandler]
class=FileHandler
level=DEBUG
formatter=LogFormatter
args=('/var/log/castools/castools.log',)

[formatter_LogFormatter]
format=%(asctime)s %(levelname)s/%(lineno)dL/%(process)s: %(message)s
datefmt=
