#
# common required
#
spring.application.name=vmware-api-server
# For supporting port configuration, vmware_api_port is configured in filesystem, located in /etc/cvk/system_ports
# If it does not exist, use default port 6061
server.port=${vmware_api_port:6061}
server.servlet.context-path=/vmware/vcenter
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
server.ssl.enabled=true
server.ssl.key-store=classpath:vmware_api_server_https.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=ENC(gzrU3jTdJhhPSn8mLY1jsIzMBeZaoE1D)
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,\
  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,\
  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,\
  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,\
  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,\
  TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,\
  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,\
  TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,\
  TLS_RSA_WITH_AES_256_GCM_SHA384,\
  TLS_RSA_WITH_AES_128_GCM_SHA256

debug.mode = ${DEBUG:false}
vmware.agent.port=${VMWARE_AGENT_PORT:6062}
vmware.agent.protocol=${VMWARE_AGENT_PROTOCOL:https}

cas.cvm.port=${tomcat_http_port:8080}

cas.cvm.ip=${CAS_CVM_IP:127.0.0.1}
