#!/bin/sh

# Platform-specific version of pkg-config
# Platform----x86_64-NingOS-linux-gnu

export PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR:-/usr/lib64/pkgconfig:/usr/share/pkgconfig}"
export PKG_CONFIG_SYSTEM_INCLUDE_PATH="${PKG_CONFIG_SYSTEM_INCLUDE_PATH:-/usr/include}"
export PKG_CONFIG_SYSTEM_LIBRARY_PATH="${PKG_CONFIG_SYSTEM_LIBRARY_PATH:-/usr/lib64}"

exec pkgconf "$@"
