## Need to check the list of deb installation packages
##ovs install package
#openvswitch ovs/openvswitch*amd64.deb

##ocfs install package
#ocfs2-modules ocfs2/ocfs2_kernel_modules.deb
#ocfs2-tools ocfs2/ocfs2-tools*amd64.deb

##libvirt install package
#libvirt0 libvirt/libvirt0*amd64.deb
#libvirt-clients libvirt/libvirt-clients*amd64.deb
#libvirt-daemon  libvirt/libvirt-daemon_*amd64.deb
#libvirt-dev libvirt/libvirt-dev*amd64.deb

##kvm install package
#kvm-ipxe qemu/kvm-ipxe*amd64.deb
#qemu-kvm qemu/qemu-kvm*amd64.deb
#qemu-common qemu/qemu-common*amd64.deb
#qemu-utils  qemu/qemu-utils*amd64.deb

##web install package which is not deb
#casfront yes
