mon_frontend_server_port = 20041;
mon_backend_server_port = 20044;
mon_fdt_server_port = 20100;
mon_cvkagent_server_port = 20047;
ha_frontend_server_port = 20043;
ha_backend_server_port = 20042;
ha_cvm_server_port = 20045;
ha_cvk_server_port = 20046;
