[loggers]
keys=root,SysprepLibguestfs

[handlers]
keys=LogHandler

[formatters]
keys=LogFormatter

[logger_root]
level=DEBUG
handlers=LogHandler

[logger_SysprepLibguestfs]
level=DEBUG
handlers=LogHandler
qualname=SysprepLibguestfs
propagate=0

[handler_LogHandler]
class=FileHandler
level=INFO
formatter=LogFormatter
args=('/var/log/castools/sysprep.log',)

[formatter_LogFormatter]
format=%(asctime)s %(levelname)s/%(lineno)dL/%(process)s: %(message)s
datefmt=
