ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE Nullable(Decimal128(2))  DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE Nullable(Decimal128(2)) DEFAULT NULL;

ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));


ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.TBL_DOMAIN_CPU_DETAIL ADD COLUMN IF NOT EXISTS CPU_READY Nullable(Decimal128(2)) DEFAULT NULL;

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));