# jdbc.X
clickhouse.jdbc.driverClassName=com.clickhouse.jdbc.ClickHouseDriver
clickhouse.jdbc.url=jdbc:clickhouse://localhost:8123/metrics?rewriteBatchedStatements=true
clickhouse.jdbc.username=xYFZQgBNw0E=
clickhouse.jdbc.password=egJU1XOSiZHypdQZAaae9g==
