default-lease-time 2592000;
preferred-lifetime 604800;
option dhcp-renewal-time 3600;
option dhcp-rebinding-time 7200;

option dhcp6.bootfile-url code 59 = string;

# Enable RFC 5007 support (same than for DHCPv4)
allow leasequery;

option dhcp6.client-arch-type code 61 = array of unsigned integer 16;
 
option dhcp6.name-servers 3ffe:501:ffff:100:200:ff:fe00:3f3e;
option dhcp6.domain-search "test.example.com","example.com";

option dhcp6.info-refresh-time 21600;

if option dhcp6.client-arch-type = 00:07 {
    option dhcp6.bootfile-url "tftp://[2001:252:4000:2000::61]/grubnetx64.efi";
} else {
    option dhcp6.bootfile-url "tftp://[2001:252:4000:2000::61]/pxelinux.0";
}

subnet6 2001:252:4000:2000::/64 {
    range6 2001:252:4000:2000::129 2001:252:4000:2000::254;
    range6 2001:252:4000:2000:: temporary;
}

