redis.maxIdle=10
redis.minIdle=0
redis.maxTotal=100
redis.maxWaitMillis=100000
redis.testOnBorrow=true
redis.testWhileIdle=true
redis.host=127.0.0.1
redis.port=6379
redis.password=COT723vi0xiIHjhUYAEddg==
redis.database=0
redis.address=redis://127.0.0.1:6379