INSERT INTO TBL_PARAMETER(TYPE, NAME, VALUE) SELECT 'sys_conf', 'i18n.language', 'zh-CN' WHERE NOT EXISTS(SELECT * FROM TBL_PARAMETER WHERE NAME = 'i18n.language');

update TBL_PARAMETER set value='5.5,6.0' where name='VIXDISKLIB_FLAG_DEFAULT';

update TBL_PARAMETER set value='6.5,6.7,7.0' where name='VIXDISKLIB_FLAG_OPEN_COMPRESSION_ZLIB';