#
# common required
#
spring.application.name=bare-metal-server
server.port=${PORT:33333}
server.servlet.context-path=/bareMetal

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

server.ssl.enabled=true
server.ssl.key-store=classpath:bareMetalServer.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=ENC(CL7pldMlv8K3fCMwWLMU2Vb6V2Q5ALW2)
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,\
  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,\
  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,\
  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,\
  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,\
  TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,\
  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,\
  TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,\
  TLS_RSA_WITH_AES_256_GCM_SHA384,\
  TLS_RSA_WITH_AES_128_GCM_SHA256


debug.mode = ${DEBUG:false}

cas.cvm.port=${CAS_CVM_PORT:8080}

cas.cvm.ip=${CAS_CVM_IP:127.0.0.1}

spring.datasource.druid.url=${jdbc.url.baremetal}
spring.datasource.druid.username=${jdbc.username}
spring.datasource.druid.password=${jdbc.password}
spring.datasource.druid.driverClassName=${jdbc.driverClassName}
spring.datasource.druid.db-type=postgresql

#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#logging.level.com.baomidou.mybatisplus=DEBUG
#\u9879\u76eemapper\u76ee\u5f55
#logging.level.com.h3c.h3cloud.bare.metal.mapper=DEBUG
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
