#!/bin/bash

log_file=/var/log/smartdev/vdpa-ctl.log
curtime=$(date +'%Y-%m-%d %H:%M:%S')
case $0 in
    */*) dir0=`echo "$0" | sed 's,/[^/]*$,,'` ;;
    *) dir0=./ ;;
esac

for dir in "$sbindir" "$bindir" /sbin /bin /usr/sbin /usr/bin; do
    case :$PATH: in
        *:$dir:*) ;;
        *) PATH=$PATH:$dir ;;
    esac
done

## help functions ##

set_option() {
    var=`echo "$option" | tr abcdefghijklmnopqrstuvwxyz- ABCDEFGHIJKLMNOPQRSTUVWXYZ_`
    eval set=\${$var+yes}
    eval old_value=\$$var
    if test X$set = X || \
        (test $type = bool && \
        test X"$old_value" != Xno && test X"$old_value" != Xyes); then
        echo >&2 "$0: unknown option \"$arg\" (use --help for help)"
        return
    fi
    eval $var=\$value
}

pid_exists() {
    # This is better than "kill -0" because it doesn't require permission to
    # send a signal (so daemon_status in particular works as non-root).
    test -d /proc/"$1"
}

pid_comm_check() {
    [ "$1" = "`cat /proc/$2/comm`" ]
}

DAEMON_CWD=/

LC_ALL=C; export LC_ALL

## ------------- ##
## LSB functions ##
## ------------- ##

# Use the system's own implementations if it has any.
if test -e /etc/init.d/functions; then
    . /etc/init.d/functions
elif test -e /etc/rc.d/init.d/functions; then
    . /etc/rc.d/init.d/functions
elif test -e /lib/lsb/init-functions; then
    . /lib/lsb/init-functions
fi

# Implement missing functions (e.g. OpenSUSE lacks 'action').
if type log_success_msg >/dev/null 2>&1; then :; else
    log_success_msg() {
        printf '%s.\n' "$curtime --- $*" >> $log_file
    }
fi
if type log_failure_msg >/dev/null 2>&1; then :; else
    log_failure_msg() {
        printf '%s ... failed!\n' "$curtime --- $*" >> $log_file
    }
fi
if type log_warning_msg >/dev/null 2>&1; then :; else
    log_warning_msg() {
        printf '%s ... (warning).\n' "$curtime --- $*" >> $log_file
    }
fi
if type action >/dev/null 2>&1; then :; else
    action() {
       STRING=$1
       shift
       "$@"
       rc=$?
       if test $rc = 0; then
            log_success_msg "$STRING"
       else
            log_failure_msg "$STRING"
       fi
       return $rc
    }
fi

install_dir() {
    DIR="$1"
    INSTALL_MODE="${2:-755}"
    INSTALL_USER="root"
    INSTALL_GROUP="root"
    [ "$OVS_USER" != "" ] && INSTALL_USER="${OVS_USER%:*}"
    [ "${OVS_USER##*:}" != "" ] && INSTALL_GROUP="${OVS_USER##*:}"

    if test ! -d "$DIR"; then
        install -d -m "$INSTALL_MODE" -o "$INSTALL_USER" -g "$INSTALL_GROUP" "$DIR"
        restorecon "$DIR" >/dev/null 2>&1
    fi
}

## daemon functions ##

daemons() {
    echo vdpa
}

get_vfs() {
    read -d '' req <<EOF
<request>
  <operationType>get</operationType>
  <iterator>sys_class_net</iterator>
  <select>
    <isPhysicalSmartNIC>1</isPhysicalSmartNIC>
  </select>
  <data>
    <name/>
    <isFullOffloaded/>
    <smartvirtualFunctions/>
  </data>
</request>
EOF

    ret=$(/bin/python3 /opt/bin/device_config.pyc --xml "$req")
    /bin/python3 - "$ret" <<EOF
import sys
import os
from xml.etree import cElementTree as ET
reply = ET.fromstring(sys.argv[1])
for ent in reply.findall("entity"):
    vfs_text = ent.find("smartvirtualFunctions").text
    vfpcis = vfs_text.split(',') if vfs_text else []
    for pci in vfpcis:
        print(pci)
EOF
}

get_iface_infos() {
    glob_files=/run/libvirt/qemu/*.xml
    if [ ! -f "$glob_files" ]; then
        return
    fi
    awk -f - $glob_files  <<'EOF'
function reset() {
    flag = 0
    mac = vdpasock = iface = ""
}
function do_parse() {
    if ($0 ~ /<interface/) {
        flag = 1
    }
    if (!flag) {
        return
    }
    if ($0 ~ /<\/interface>/) {
        if (flag == 1) {
            if (mac && vdpasock && iface) {
                printf("%s /var/run/vdpa/device/%s %s\n", mac, vdpasock, iface)
            }
            reset()
        }
    } else if (match($0, /mac address='([^']*)'/, m)) {
        mac = m[1]
    } else if (match($0, /target dev='([^']*)'/, m)) {
        iface = m[1]
    } else if (match($0, /\/var\/run\/vdpa\/device\/([^']*)/, m)) {
        vdpasock = m[1]
    }
}
BEGIN { reset() }
{ do_parse() }
EOF
}

ensure_roce() {
    # idms: 202112150908
    rep_list=$(ovs-vsctl -t 2 --bare --format=table --columns=name find Int other_config:used_by_subnet=1)
    rep_to_vport=$(python3 /opt/bin/ovs_smartnic.pyc lsvdpa --verbose | awk '{print $2,$3}')
    for rep in $rep_list; do
        vport_pci=$(grep "^$rep" <<<"$rep_to_vport" | awk '{print $2}')
        if [ X"$vport_pci" != X"" ]; then
            devlink dev param set pci/$vport_pci name enable_roce value true cmode driverinit
            devlink dev reload pci/$vport_pci
        fi
    done
}

start_daemon() {
    daemon=$1
    if test -f /etc/cvk/cas_offload.conf; then
        source /etc/cvk/cas_offload.conf
    fi
    # drop core files in a sensible place
    install_dir "$DAEMON_CWD"
    cd "$DAEMON_CWD"

    # log file
    #install_dir "$logdir" "750"
    #set "$@" --log-file="$logdir/$daemon.log"

    # pidfile and monitoring
    install_dir "$rundir"

    # vdpa exec example: vdpa -w 0000:af:01.2,class=vdpa -w 0000:af:01.3,class=vdpa -- --detach --unixserver --client
    if [ "X$VDPA_PCIS_OVERRIDE" != "X" ]; then
        vfpcis=$VDPA_PCIS_OVERRIDE
    else
        vfpcis=$(get_vfs)
    fi

    if [ -z "$vfpcis" ]; then
        log_success_msg "No need to start vdpa.service for has no vfpcis."
        return 0
    fi

    if [ "X$VDPA_EVENT_MODE" = "X" ]; then
        VDPA_EVENT_MODE=1
    fi
    if [ "X$VDPA_EVENT_US" = "X" ]; then
        VDPA_EVENT_US=5
    fi

    local vf_num=0
    for vfpci in $vfpcis; do
        ((vf_num++))
        set "$@" -a $vfpci,class=vdpa,event_mode=$VDPA_EVENT_MODE,event_us=$VDPA_EVENT_US
    done

    set "$@" --file-prefix vdpa
    set "$@" --
    set "$@" --detach
    set "$@" --unixserver
    set "$@" --client
    
    # priority
    if test X"$priority" != X; then
        set nice -n "$priority" "$@"
    fi

    # in case of vpda exception, the sock file is valid
    unlink $rundir/$daemon.sock 2>/dev/null
    
    echo "$curtime --- Starting $daemon" >> $log_file
    "$@" 

    # handle vdpa exit exceptionally, wait the sock file to appear
    cnt=0
    ((time_out=vf_num*35)) #set timeout for waiting vdpa init complete, time_out = vf_num * 35.
    echo "$curtime --- Wait vdpa time_out: $time_out" >> $log_file
    while ! test -e "$rundir/$daemon.sock"; do
        sleep 0.1s
        ((cnt++))
        if [ $time_out -gt 0 ]; then   
            if [ $cnt -gt $time_out ]; then
                echo "$curtime --- Wait vdpa to appear timed out" >> $log_file
                ensure_roce
                exit 1
            fi
        else
            if [ $cnt -gt 300 ]; then
                echo "$curtime --- Wait vdpa to appear timed out" >> $log_file
                ensure_roce
                exit 1
            fi
        fi
    done
    echo "$curtime --- Wait vdpa time $cnt" >> $log_file
    vdpadevlist=$(python3 /opt/bin/ovs_smartnic.pyc lsvdpa)
    lstnsocks=$(ss -ax | grep 'LISTEN.*/var/run/vdpa/device/vdpa_' | awk '{print $5}')

    if [ "X$VDPA_RESTORE_SOCK" != "Xfalse" ]; then
        infos=$(get_iface_infos)
        for lstnsock in $lstnsocks; do
            iface=$(echo -n "$infos" | grep $lstnsock | awk '{print $3}')
            if test -n "$iface"; then
                bdbf=$(echo "$vdpadevlist" | grep "\b$iface\b" | awk '{print $3}')
                if test -n "$bdbf"; then
                    vdpactl create $lstnsock $bdbf
                fi
            fi
        done
    fi

    ensure_roce
}

remove_unlocked_vdpa_hugepages() {
    for filepath in $(ls /dev/hugepages/vdpamap_* 2>/dev/null || true)
    do
        if flock -oxn "$filepath" -c "rm -f $filepath";then
            log_success_msg "remove unlocked hugepage $filepath"
        fi
    done
}

stop_daemon() {
    if test -e "$rundir/$1.pid"; then
        if pid=`cat "$rundir/$1.pid"`; then
            actions="EXIT .1 .25 .65 1 1 1 \
                     TERM .1 .25 .65 1 1 \
                     KILL 1 1 1 2 10 15 30 \
                     FAIL"

            for action in $actions; do
                if pid_exists "$pid" >/dev/null 2>&1; then :; else
                    return 0
                fi
                case $action in
                    EXIT)
			${bindir}/vdpactl exit
                        log_success_msg "Exiting $1 ($pid)"
                        ;;
                    TERM)
			kill $pid
                        log_success_msg "Killing $1 ($pid)"
                        ;;
                    KILL)
			kill -9 $pid
                        log_success_msg "Killing $1 ($pid) with SIGKILL"
                        ;;
                    FAIL)
                        log_failure_msg "Killing $1 ($pid) failed"
                        return 1
                        ;;
                    *)
			log_success_msg "stop daemon sleep $action"
                        sleep $action
                        ;;
                esac
            done
        fi
    fi
    log_success_msg "$1 is not running"
}

daemon_status() {
    pidfile=$rundir/$1.pid
    if test -e "$pidfile"; then
        if pid=`cat "$pidfile"`; then
            if pid_exists "$pid"; then
                echo "$1 is running with pid $pid"
                return 0
            else
                echo "Pidfile for $1 ($pidfile) is stale"
            fi
        else
            echo "Pidfile for $1 ($pidfile) exists but cannot be read"
        fi
    else
        echo "$1 is not running"
    fi
    return 1
}

daemon_is_running() {
    pidfile=$rundir/$1.pid
    test -e "$pidfile" && pid=`cat "$pidfile"` && pid_exists "$pid" && pid_comm_check $1 $pid
} >/dev/null 2>&1

## start ##

start_vdpa() {
    if daemon_is_running vdpa; then
        log_success_msg "vdpa is already running"
    else
        start_daemon vdpa
    fi
}

## stop ##

stop_vdpa() {
    stop_daemon vdpa
    remove_unlocked_vdpa_hugepages
}

## main ##

set_defaults() {
    SYSTEM_ID=
    DAEMON_CWD=/
    rundir=/var/run/vdpa/
    bindir=/usr/bin/
}

usage() {
    cat <<EOF
$0: controls vdpa daemons
usage: $0 [OPTIONS] COMMAND

This program is intended to be invoked internally by vdpa startup
scripts.  System administrators should not normally invoke it directly.

Commands:
  start                   start vdpa daemons
  stop                    stop vdpa daemons
EOF

    exit 0
}

VERSION=1.0
set_defaults
extra_ids=
command=
for arg; do
    case $arg in
        -h | --help)
            usage
            ;;
        -V | --version)
            echo "$0 (vdpa) $VERSION"
            exit 0
            ;;
        --[a-z]*=*)
            option=`expr X"$arg" : 'X--\([^=]*\)'`
            value=`expr X"$arg" : 'X[^=]*=\(.*\)'`
            type=string
            set_option
            ;;
        --no-[a-z]*)
            option=`expr X"$arg" : 'X--no-\(.*\)'`
            value=no
            type=bool
            set_option
            ;;
        --[a-z]*)
            option=`expr X"$arg" : 'X--\(.*\)'`
            value=yes
            type=bool
            set_option
            ;;
        -*)
            echo >&2 "$0: unknown option \"$arg\" (use --help for help)"
            exit 1
            ;;
        *)
            if test X"$command" = X; then
                command=$arg
            else
                echo >&2 "$0: exactly one non-option argument required (use --help for help)"
                exit 1
            fi
            ;;
    esac
done
case $command in
    start)
        start_vdpa || exit 1
        ;;
    stop)
        stop_vdpa
        ;;
    restart)
        restart
        ;;
    status)
        rc=0
        for daemon in `daemons`; do
            daemon_status $daemon || rc=$?
        done
        exit $rc
        ;;
    version)
        for daemon in `daemons`; do
            $daemon --version
        done
        ;;
    help)
        usage
        ;;
    '')
        echo >&2 "$0: missing command name (use --help for help)"
        exit 1
        ;;
    *)
        echo >&2 "$0: unknown command \"$command\" (use --help for help)"
        exit 1
        ;;
esac
