# RoCE network requires QoS and no packet drops (loss-less), need to configure PFC.

# The default trust state is pcp. Ethernet packets are prioritized based on the value of the field (pcp/dscp).
# Trust=pcp using pcp bits on the VLAN header (L2).
# Trust=dscp using dscp bits on the IP header (L3).
pfc_trust=pcp

# PFC should be enabled on the proper priority that is mapped to the TC that we wish to have no drops on.
# pfc_priority must be range [0, 7].
pfc_priority=3

# The ToS field is 8 bits, while the DSCP field is 6 bits. To set a DSCP value of X, you need to multiply this value by 4 (SHIFT 2).
# For example, to set DSCP value of 26, set the ToS bit to 104 (26x4=104).
# pfc_tos can be used when pfc_trust equl dscp.
pfc_tos=104

