DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_5M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_30M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1H;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1D;
DROP VIEW IF EXISTS metrics.VIEW_HOST_NIC_FLOW_5M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_NIC_FLOW_30M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_NIC_FLOW_1H;
DROP VIEW IF EXISTS metrics.VIEW_HOST_NIC_FLOW_1D;
DROP VIEW IF EXISTS metrics.VIEW_HOST_IO_STAT_5M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_IO_STAT_30M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_IO_STAT_1H;
DROP VIEW IF EXISTS metrics.VIEW_HOST_IO_STAT_1D;
DROP VIEW IF EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_5M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_30M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_1H;
DROP VIEW IF EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_1D;
DROP VIEW IF EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_5M;
DROP VIEW IF EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_30M;
DROP VIEW IF EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_1H;
DROP VIEW IF EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_1D;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_FLOW_5M;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_FLOW_30M;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_FLOW_1H;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_FLOW_1D;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_5M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_30M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_1H;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_1D;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_5M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_30M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_1H;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_1D;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_IO_STAT_5M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_IO_STAT_30M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_IO_STAT_1H;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_IO_STAT_1D;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_GPU_STAT_5M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_GPU_STAT_30M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_GPU_STAT_1H;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_GPU_STAT_1D;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_5M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_30M;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_1H;
DROP VIEW IF EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_1D;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_5M;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_30M;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_1H;
DROP VIEW IF EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_1D;
DROP VIEW IF EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_5M;
DROP VIEW IF EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_30M;
DROP VIEW IF EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_1H;
DROP VIEW IF EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_1D;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_5M
TO metrics.AGG_FC_STORAGE_ERROR_CODE_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
	    PHYSIC_PORT,
      maxState(ERROR_FRAMES) AS ERROR_FRAMES_MAX,
      minState(ERROR_FRAMES) AS ERROR_FRAMES_MIN,
      avgState(ERROR_FRAMES) AS ERROR_FRAMES_AVG,
      sumState(ERROR_FRAMES) AS ERROR_FRAMES_SUM,
      maxState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MAX,
      minState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MIN,
      avgState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_AVG,
      sumState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_SUM,
	    maxState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MAX,
      minState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MIN,
      avgState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_AVG,
      sumState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_SUM,
	    maxState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MAX,
      minState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MIN,
      avgState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_AVG,
      sumState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_SUM,
	    maxState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MAX,
      minState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MIN,
      avgState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_AVG,
      sumState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_SUM,
	    maxState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MAX,
      minState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MIN,
      avgState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_AVG,
      sumState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_SUM
   FROM metrics.TBL_FC_STORAGE_ERROR_CODE GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PHYSIC_PORT, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_30M
TO metrics.AGG_FC_STORAGE_ERROR_CODE_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
	    PHYSIC_PORT,
      maxState(ERROR_FRAMES) AS ERROR_FRAMES_MAX,
      minState(ERROR_FRAMES) AS ERROR_FRAMES_MIN,
      avgState(ERROR_FRAMES) AS ERROR_FRAMES_AVG,
      sumState(ERROR_FRAMES) AS ERROR_FRAMES_SUM,
      maxState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MAX,
      minState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MIN,
      avgState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_AVG,
      sumState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_SUM,
	    maxState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MAX,
      minState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MIN,
      avgState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_AVG,
      sumState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_SUM,
	    maxState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MAX,
      minState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MIN,
      avgState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_AVG,
      sumState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_SUM,
	    maxState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MAX,
      minState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MIN,
      avgState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_AVG,
      sumState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_SUM,
	    maxState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MAX,
      minState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MIN,
      avgState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_AVG,
      sumState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_SUM
   FROM metrics.TBL_FC_STORAGE_ERROR_CODE GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PHYSIC_PORT, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_1H
TO metrics.AGG_FC_STORAGE_ERROR_CODE_1H
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
	    PHYSIC_PORT,
      maxState(ERROR_FRAMES) AS ERROR_FRAMES_MAX,
      minState(ERROR_FRAMES) AS ERROR_FRAMES_MIN,
      avgState(ERROR_FRAMES) AS ERROR_FRAMES_AVG,
      sumState(ERROR_FRAMES) AS ERROR_FRAMES_SUM,
      maxState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MAX,
      minState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MIN,
      avgState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_AVG,
      sumState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_SUM,
	    maxState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MAX,
      minState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MIN,
      avgState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_AVG,
      sumState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_SUM,
	    maxState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MAX,
      minState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MIN,
      avgState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_AVG,
      sumState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_SUM,
	    maxState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MAX,
      minState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MIN,
      avgState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_AVG,
      sumState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_SUM,
	    maxState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MAX,
      minState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MIN,
      avgState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_AVG,
      sumState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_SUM
   FROM metrics.TBL_FC_STORAGE_ERROR_CODE GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PHYSIC_PORT, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_FC_STORAGE_ERROR_CODE_1D
TO metrics.AGG_FC_STORAGE_ERROR_CODE_1D
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
	    PHYSIC_PORT,
      maxState(ERROR_FRAMES) AS ERROR_FRAMES_MAX,
      minState(ERROR_FRAMES) AS ERROR_FRAMES_MIN,
      avgState(ERROR_FRAMES) AS ERROR_FRAMES_AVG,
      sumState(ERROR_FRAMES) AS ERROR_FRAMES_SUM,
      maxState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MAX,
      minState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_MIN,
      avgState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_AVG,
      sumState(INVALID_CRC_COUNT) AS INVALID_CRC_COUNT_SUM,
	    maxState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MAX,
      minState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_MIN,
      avgState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_AVG,
      sumState(LOSS_OF_SIGNAL_COUNT) AS LOSS_OF_SIGNAL_COUNT_SUM,
	    maxState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MAX,
      minState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_MIN,
      avgState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_AVG,
      sumState(LOSS_OF_SYNC_COUNT) AS LOSS_OF_SYNC_COUNT_SUM,
	    maxState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MAX,
      minState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_MIN,
      avgState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_AVG,
      sumState(LINK_FAILURE_COUNT) AS LINK_FAILURE_COUNT_SUM,
	    maxState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MAX,
      minState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_MIN,
      avgState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_AVG,
      sumState(INVALID_TX_WORD_COUNT) AS INVALID_TX_WORD_COUNT_SUM
   FROM metrics.TBL_FC_STORAGE_ERROR_CODE GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PHYSIC_PORT, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_5M
TO metrics.AGG_HOST_CPU_MEM_DETAIL_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_30M
TO metrics.AGG_HOST_CPU_MEM_DETAIL_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1H
TO metrics.AGG_HOST_CPU_MEM_DETAIL_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1D
TO metrics.AGG_HOST_CPU_MEM_DETAIL_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_NIC_FLOW_5M
TO metrics.AGG_HOST_NIC_FLOW_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      MAC,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
      maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
      maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
      maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
      maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
      maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG
   FROM metrics.TBL_HOST_NIC_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, MAC, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_NIC_FLOW_30M
TO metrics.AGG_HOST_NIC_FLOW_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      MAC,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
      maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
      maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
      maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
      maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
      maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG
   FROM metrics.TBL_HOST_NIC_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, MAC, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_NIC_FLOW_1H
TO metrics.AGG_HOST_NIC_FLOW_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      MAC,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
      maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
      maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
      maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
      maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
      maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG
   FROM metrics.TBL_HOST_NIC_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, MAC, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_NIC_FLOW_1D
TO metrics.AGG_HOST_NIC_FLOW_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      MAC,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
      maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
      maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
      maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
      maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
      maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG
   FROM metrics.TBL_HOST_NIC_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, MAC, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_IO_STAT_5M
TO metrics.AGG_HOST_IO_STAT_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
      maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
      maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
      maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG
   FROM metrics.TBL_HOST_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_IO_STAT_30M
TO metrics.AGG_HOST_IO_STAT_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
      maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
      maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
      maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG
   FROM metrics.TBL_HOST_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_IO_STAT_1H
TO metrics.AGG_HOST_IO_STAT_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
      maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
      maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
      maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG
   FROM metrics.TBL_HOST_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_IO_STAT_1D
TO metrics.AGG_HOST_IO_STAT_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
      maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
      maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
      maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG
   FROM metrics.TBL_HOST_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_5M
TO metrics.AGG_HOST_PARTITION_DETAIL_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      PARTITION_NAME,
      any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(MOUNTED_DIR) AS MOUNTED_DIR,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_HOST_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_30M
TO metrics.AGG_HOST_PARTITION_DETAIL_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      PARTITION_NAME,
      any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(MOUNTED_DIR) AS MOUNTED_DIR,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_HOST_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_1H
TO metrics.AGG_HOST_PARTITION_DETAIL_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      PARTITION_NAME,
      any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(MOUNTED_DIR) AS MOUNTED_DIR,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_HOST_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_PARTITION_DETAIL_1D
TO metrics.AGG_HOST_PARTITION_DETAIL_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      PARTITION_NAME,
      any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(MOUNTED_DIR) AS MOUNTED_DIR,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
      maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
      maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_HOST_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_5M
TO metrics.AGG_STORAGE_MULTIPATH_IO_STAT_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(POOL_NAME) AS POOL_NAME,
      any(NAA) AS NAA,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_STORAGE_MULTIPATH_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_30M
TO metrics.AGG_STORAGE_MULTIPATH_IO_STAT_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(POOL_NAME) AS POOL_NAME,
      any(NAA) AS NAA,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_STORAGE_MULTIPATH_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_1H
TO metrics.AGG_STORAGE_MULTIPATH_IO_STAT_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(POOL_NAME) AS POOL_NAME,
      any(NAA) AS NAA,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_STORAGE_MULTIPATH_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_STORAGE_MULTIPATH_IO_STAT_1D
TO metrics.AGG_STORAGE_MULTIPATH_IO_STAT_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DEV_NAME,
      any(POOL_NAME) AS POOL_NAME,
      any(NAA) AS NAA,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
      maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
      maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_STORAGE_MULTIPATH_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_FLOW_5M
TO metrics.AGG_VSWITCH_FLOW_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(TX_ERROR_RATE) AS TX_ERROR_RATE_MAX,
      minState(TX_ERROR_RATE) AS TX_ERROR_RATE_MIN,
      avgState(TX_ERROR_RATE) AS TX_ERROR_RATE_AVG,
	    maxState(RX_ERROR_RATE) AS RX_ERROR_RATE_MAX,
      minState(RX_ERROR_RATE) AS RX_ERROR_RATE_MIN,
      avgState(RX_ERROR_RATE) AS RX_ERROR_RATE_AVG
   FROM metrics.TBL_VSWITCH_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_FLOW_30M
TO metrics.AGG_VSWITCH_FLOW_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(TX_ERROR_RATE) AS TX_ERROR_RATE_MAX,
      minState(TX_ERROR_RATE) AS TX_ERROR_RATE_MIN,
      avgState(TX_ERROR_RATE) AS TX_ERROR_RATE_AVG,
	    maxState(RX_ERROR_RATE) AS RX_ERROR_RATE_MAX,
      minState(RX_ERROR_RATE) AS RX_ERROR_RATE_MIN,
      avgState(RX_ERROR_RATE) AS RX_ERROR_RATE_AVG
   FROM metrics.TBL_VSWITCH_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_FLOW_1H
TO metrics.AGG_VSWITCH_FLOW_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(TX_ERROR_RATE) AS TX_ERROR_RATE_MAX,
      minState(TX_ERROR_RATE) AS TX_ERROR_RATE_MIN,
      avgState(TX_ERROR_RATE) AS TX_ERROR_RATE_AVG,
	    maxState(RX_ERROR_RATE) AS RX_ERROR_RATE_MAX,
      minState(RX_ERROR_RATE) AS RX_ERROR_RATE_MIN,
      avgState(RX_ERROR_RATE) AS RX_ERROR_RATE_AVG
   FROM metrics.TBL_VSWITCH_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_FLOW_1D
TO metrics.AGG_VSWITCH_FLOW_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
      maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
      maxState(RX_DROP) AS RX_DROP_MAX,
      minState(RX_DROP) AS RX_DROP_MIN,
      avgState(RX_DROP) AS RX_DROP_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_DROP) AS TX_DROP_MAX,
      minState(TX_DROP) AS TX_DROP_MIN,
      avgState(TX_DROP) AS TX_DROP_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(TX_ERROR_RATE) AS TX_ERROR_RATE_MAX,
      minState(TX_ERROR_RATE) AS TX_ERROR_RATE_MIN,
      avgState(TX_ERROR_RATE) AS TX_ERROR_RATE_AVG,
	    maxState(RX_ERROR_RATE) AS RX_ERROR_RATE_MAX,
      minState(RX_ERROR_RATE) AS RX_ERROR_RATE_MIN,
      avgState(RX_ERROR_RATE) AS RX_ERROR_RATE_AVG
   FROM metrics.TBL_VSWITCH_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_5M
TO metrics.AGG_DOMAIN_CPU_DETAIL_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_READY) AS CPU_READY_MAX,
      minState(CPU_READY) AS CPU_READY_MIN,
      avgState(CPU_READY) AS CPU_READY_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY) AS MEMORY_MAX,
      minState(MEMORY) AS MEMORY_MIN,
      avgState(MEMORY) AS MEMORY_AVG
   FROM metrics.TBL_DOMAIN_CPU_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_30M
TO metrics.AGG_DOMAIN_CPU_DETAIL_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_READY) AS CPU_READY_MAX,
      minState(CPU_READY) AS CPU_READY_MIN,
      avgState(CPU_READY) AS CPU_READY_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY) AS MEMORY_MAX,
      minState(MEMORY) AS MEMORY_MIN,
      avgState(MEMORY) AS MEMORY_AVG
   FROM metrics.TBL_DOMAIN_CPU_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_1H
TO metrics.AGG_DOMAIN_CPU_DETAIL_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_READY) AS CPU_READY_MAX,
      minState(CPU_READY) AS CPU_READY_MIN,
      avgState(CPU_READY) AS CPU_READY_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY) AS MEMORY_MAX,
      minState(MEMORY) AS MEMORY_MIN,
      avgState(MEMORY) AS MEMORY_AVG
   FROM metrics.TBL_DOMAIN_CPU_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_CPU_DETAIL_1D
TO metrics.AGG_DOMAIN_CPU_DETAIL_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_READY) AS CPU_READY_MAX,
      minState(CPU_READY) AS CPU_READY_MIN,
      avgState(CPU_READY) AS CPU_READY_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY) AS MEMORY_MAX,
      minState(MEMORY) AS MEMORY_MIN,
      avgState(MEMORY) AS MEMORY_AVG
   FROM metrics.TBL_DOMAIN_CPU_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_5M
TO metrics.AGG_DOMAIN_FLOW_LINK_STAT_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(FLOW_LINK) AS FLOW_LINK_MAX,
      minState(FLOW_LINK) AS FLOW_LINK_MIN,
      avgState(FLOW_LINK) AS FLOW_LINK_AVG
   FROM metrics.TBL_DOMAIN_FLOW_LINK_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_30M
TO metrics.AGG_DOMAIN_FLOW_LINK_STAT_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(FLOW_LINK) AS FLOW_LINK_MAX,
      minState(FLOW_LINK) AS FLOW_LINK_MIN,
      avgState(FLOW_LINK) AS FLOW_LINK_AVG
   FROM metrics.TBL_DOMAIN_FLOW_LINK_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_1H
TO metrics.AGG_DOMAIN_FLOW_LINK_STAT_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(FLOW_LINK) AS FLOW_LINK_MAX,
      minState(FLOW_LINK) AS FLOW_LINK_MIN,
      avgState(FLOW_LINK) AS FLOW_LINK_AVG
   FROM metrics.TBL_DOMAIN_FLOW_LINK_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_FLOW_LINK_STAT_1D
TO metrics.AGG_DOMAIN_FLOW_LINK_STAT_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(FLOW_LINK) AS FLOW_LINK_MAX,
      minState(FLOW_LINK) AS FLOW_LINK_MIN,
      avgState(FLOW_LINK) AS FLOW_LINK_AVG
   FROM metrics.TBL_DOMAIN_FLOW_LINK_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_IO_STAT_5M
TO metrics.AGG_DOMAIN_IO_STAT_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
	    maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
	    maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_DOMAIN_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_IO_STAT_30M
TO metrics.AGG_DOMAIN_IO_STAT_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
	    maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
	    maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_DOMAIN_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_IO_STAT_1H
TO metrics.AGG_DOMAIN_IO_STAT_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
	    maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
	    maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_DOMAIN_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_IO_STAT_1D
TO metrics.AGG_DOMAIN_IO_STAT_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    DEV_NAME,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(IO_STAT) AS IO_STAT_MAX,
      minState(IO_STAT) AS IO_STAT_MIN,
      avgState(IO_STAT) AS IO_STAT_AVG,
	    maxState(RD_STAT) AS RD_STAT_MAX,
      minState(RD_STAT) AS RD_STAT_MIN,
      avgState(RD_STAT) AS RD_STAT_AVG,
	    maxState(WR_STAT) AS WR_STAT_MAX,
      minState(WR_STAT) AS WR_STAT_MIN,
      avgState(WR_STAT) AS WR_STAT_AVG,
	    maxState(RD_REQ) AS RD_REQ_MAX,
      minState(RD_REQ) AS RD_REQ_MIN,
      avgState(RD_REQ) AS RD_REQ_AVG,
	    maxState(WR_REQ) AS WR_REQ_MAX,
      minState(WR_REQ) AS WR_REQ_MIN,
      avgState(WR_REQ) AS WR_REQ_AVG,
	    maxState(RD_REQ_PS) AS RD_REQ_PS_MAX,
      minState(RD_REQ_PS) AS RD_REQ_PS_MIN,
      avgState(RD_REQ_PS) AS RD_REQ_PS_AVG,
	    maxState(WR_REQ_PS) AS WR_REQ_PS_MAX,
      minState(WR_REQ_PS) AS WR_REQ_PS_MIN,
      avgState(WR_REQ_PS) AS WR_REQ_PS_AVG,
	    maxState(RD_LATENCY) AS RD_LATENCY_MAX,
      minState(RD_LATENCY) AS RD_LATENCY_MIN,
      avgState(RD_LATENCY) AS RD_LATENCY_AVG,
	    maxState(WR_LATENCY) AS WR_LATENCY_MAX,
      minState(WR_LATENCY) AS WR_LATENCY_MIN,
      avgState(WR_LATENCY) AS WR_LATENCY_AVG
   FROM metrics.TBL_DOMAIN_IO_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, DEV_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_GPU_STAT_5M
TO metrics.AGG_DOMAIN_GPU_STAT_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    UUID_PCI,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(MEMORY_USE) AS MEMORY_USE_MAX,
      minState(MEMORY_USE) AS MEMORY_USE_MIN,
      avgState(MEMORY_USE) AS MEMORY_USE_AVG,
	    maxState(CODE_RATE) AS CODE_RATE_MAX,
      minState(CODE_RATE) AS CODE_RATE_MIN,
      avgState(CODE_RATE) AS CODE_RATE_AVG,
	    maxState(DECODE_RATE) AS DECODE_RATE_MAX,
      minState(DECODE_RATE) AS DECODE_RATE_MIN,
      avgState(DECODE_RATE) AS DECODE_RATE_AVG
   FROM metrics.TBL_DOMAIN_GPU_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, UUID_PCI, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_GPU_STAT_30M
TO metrics.AGG_DOMAIN_GPU_STAT_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    UUID_PCI,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(MEMORY_USE) AS MEMORY_USE_MAX,
      minState(MEMORY_USE) AS MEMORY_USE_MIN,
      avgState(MEMORY_USE) AS MEMORY_USE_AVG,
	    maxState(CODE_RATE) AS CODE_RATE_MAX,
      minState(CODE_RATE) AS CODE_RATE_MIN,
      avgState(CODE_RATE) AS CODE_RATE_AVG,
	    maxState(DECODE_RATE) AS DECODE_RATE_MAX,
      minState(DECODE_RATE) AS DECODE_RATE_MIN,
      avgState(DECODE_RATE) AS DECODE_RATE_AVG
   FROM metrics.TBL_DOMAIN_GPU_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, UUID_PCI, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_GPU_STAT_1H
TO metrics.AGG_DOMAIN_GPU_STAT_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    UUID_PCI,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(MEMORY_USE) AS MEMORY_USE_MAX,
      minState(MEMORY_USE) AS MEMORY_USE_MIN,
      avgState(MEMORY_USE) AS MEMORY_USE_AVG,
	    maxState(CODE_RATE) AS CODE_RATE_MAX,
      minState(CODE_RATE) AS CODE_RATE_MIN,
      avgState(CODE_RATE) AS CODE_RATE_AVG,
	    maxState(DECODE_RATE) AS DECODE_RATE_MAX,
      minState(DECODE_RATE) AS DECODE_RATE_MIN,
      avgState(DECODE_RATE) AS DECODE_RATE_AVG
   FROM metrics.TBL_DOMAIN_GPU_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, UUID_PCI, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_GPU_STAT_1D
TO metrics.AGG_DOMAIN_GPU_STAT_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    UUID_PCI,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(MEMORY_USE) AS MEMORY_USE_MAX,
      minState(MEMORY_USE) AS MEMORY_USE_MIN,
      avgState(MEMORY_USE) AS MEMORY_USE_AVG,
	    maxState(CODE_RATE) AS CODE_RATE_MAX,
      minState(CODE_RATE) AS CODE_RATE_MIN,
      avgState(CODE_RATE) AS CODE_RATE_AVG,
	    maxState(DECODE_RATE) AS DECODE_RATE_MAX,
      minState(DECODE_RATE) AS DECODE_RATE_MIN,
      avgState(DECODE_RATE) AS DECODE_RATE_AVG
   FROM metrics.TBL_DOMAIN_GPU_STAT GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, UUID_PCI, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_5M
TO metrics.AGG_DOMAIN_PARTITION_DETAIL_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    PARTITION_NAME,
	    any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_DOMAIN_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_30M
TO metrics.AGG_DOMAIN_PARTITION_DETAIL_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      PARTITION_NAME,
      any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_DOMAIN_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_1H
TO metrics.AGG_DOMAIN_PARTITION_DETAIL_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    PARTITION_NAME,
	    any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_DOMAIN_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_DOMAIN_PARTITION_DETAIL_1D
TO metrics.AGG_DOMAIN_PARTITION_DETAIL_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    PARTITION_NAME,
	    any(PARTITION_TYPE) AS PARTITION_TYPE,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(UTILIZATION) AS UTILIZATION_MAX,
      minState(UTILIZATION) AS UTILIZATION_MIN,
      avgState(UTILIZATION) AS UTILIZATION_AVG,
	    maxState(SIZE) AS SIZE_MAX,
      minState(SIZE) AS SIZE_MIN,
      avgState(SIZE) AS SIZE_AVG,
	    maxState(USED) AS USED_MAX,
      minState(USED) AS USED_MIN,
      avgState(USED) AS USED_AVG
   FROM metrics.TBL_DOMAIN_PARTITION_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, PARTITION_NAME, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_5M
TO metrics.AGG_VSWITCH_PORT_FLOW_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    MAC,
	    VSWITCH_ID,
	    any(VSWITCH_NAME) AS VSWITCH_NAME,
	    any(VPORT) AS VPORT,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
	    maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MAX,
      minState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MIN,
      avgState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_AVG,
	    maxState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MAX,
      minState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MIN,
      avgState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_AVG,
	    maxState(RX_BYTES) AS RX_BYTES_MAX,
      minState(RX_BYTES) AS RX_BYTES_MIN,
      avgState(RX_BYTES) AS RX_BYTES_AVG,
	    maxState(TX_BYTES) AS TX_BYTES_MAX,
      minState(TX_BYTES) AS TX_BYTES_MIN,
      avgState(TX_BYTES) AS TX_BYTES_AVG
   FROM metrics.TBL_VSWITCH_PORT_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, MAC, VSWITCH_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_30M
TO metrics.AGG_VSWITCH_PORT_FLOW_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
	    MAC,
	    VSWITCH_ID,
	    any(VSWITCH_NAME) AS VSWITCH_NAME,
	    any(VPORT) AS VPORT,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
	    maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MAX,
      minState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MIN,
      avgState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_AVG,
	    maxState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MAX,
      minState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MIN,
      avgState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_AVG,
	    maxState(RX_BYTES) AS RX_BYTES_MAX,
      minState(RX_BYTES) AS RX_BYTES_MIN,
      avgState(RX_BYTES) AS RX_BYTES_AVG,
	    maxState(TX_BYTES) AS TX_BYTES_MAX,
      minState(TX_BYTES) AS TX_BYTES_MIN,
      avgState(TX_BYTES) AS TX_BYTES_AVG
   FROM metrics.TBL_VSWITCH_PORT_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, MAC, VSWITCH_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_1H
TO metrics.AGG_VSWITCH_PORT_FLOW_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      MAC,
      VSWITCH_ID,
      any(VSWITCH_NAME) AS VSWITCH_NAME,
      any(VPORT) AS VPORT,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
	    maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MAX,
      minState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MIN,
      avgState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_AVG,
	    maxState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MAX,
      minState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MIN,
      avgState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_AVG,
	    maxState(RX_BYTES) AS RX_BYTES_MAX,
      minState(RX_BYTES) AS RX_BYTES_MIN,
      avgState(RX_BYTES) AS RX_BYTES_AVG,
	    maxState(TX_BYTES) AS TX_BYTES_MAX,
      minState(TX_BYTES) AS TX_BYTES_MIN,
      avgState(TX_BYTES) AS TX_BYTES_AVG
   FROM metrics.TBL_VSWITCH_PORT_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, MAC, VSWITCH_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_VSWITCH_PORT_FLOW_1D
TO metrics.AGG_VSWITCH_PORT_FLOW_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      DOMAIN_ID,
      MAC,
      VSWITCH_ID,
      any(VSWITCH_NAME) AS VSWITCH_NAME,
      any(VPORT) AS VPORT,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(RX_FLOW) AS RX_FLOW_MAX,
      minState(RX_FLOW) AS RX_FLOW_MIN,
      avgState(RX_FLOW) AS RX_FLOW_AVG,
	    maxState(RX_PACKETS) AS RX_PACKETS_MAX,
      minState(RX_PACKETS) AS RX_PACKETS_MIN,
      avgState(RX_PACKETS) AS RX_PACKETS_AVG,
	    maxState(RX_ERR) AS RX_ERR_MAX,
      minState(RX_ERR) AS RX_ERR_MIN,
      avgState(RX_ERR) AS RX_ERR_AVG,
	    maxState(TX_FLOW) AS TX_FLOW_MAX,
      minState(TX_FLOW) AS TX_FLOW_MIN,
      avgState(TX_FLOW) AS TX_FLOW_AVG,
	    maxState(TX_PACKETS) AS TX_PACKETS_MAX,
      minState(TX_PACKETS) AS TX_PACKETS_MIN,
      avgState(TX_PACKETS) AS TX_PACKETS_AVG,
	    maxState(TX_ERR) AS TX_ERR_MAX,
      minState(TX_ERR) AS TX_ERR_MIN,
      avgState(TX_ERR) AS TX_ERR_AVG,
	    maxState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MAX,
      minState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_MIN,
      avgState(RX_DROPPED_PACKETS) AS RX_DROPPED_PACKETS_AVG,
	    maxState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MAX,
      minState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_MIN,
      avgState(TX_DROPPED_PACKETS) AS TX_DROPPED_PACKETS_AVG,
	    maxState(RX_BYTES) AS RX_BYTES_MAX,
      minState(RX_BYTES) AS RX_BYTES_MIN,
      avgState(RX_BYTES) AS RX_BYTES_AVG,
	    maxState(TX_BYTES) AS TX_BYTES_MAX,
      minState(TX_BYTES) AS TX_BYTES_MIN,
      avgState(TX_BYTES) AS TX_BYTES_AVG
   FROM metrics.TBL_VSWITCH_PORT_FLOW GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, DOMAIN_ID, MAC, VSWITCH_ID, TIME;