#config param in dpid

#serial device
port = "/var/lib/libvirt/qemu/dpi.agent"

#poll waiting tiem when send heart beat shankhands
hb_waiting_time = 5000

#between heart beats interval time
interval = 5

#reconnect port interval time
reconnect_interval = 5

#resend heart beat when that counts
resend_interval = 5