#! /usr/bin/python

import os

try:
    # Python 2.7 or >=3.2
    from sysconfig import get_path

    def _get_purelib():
        return get_path("purelib")
except ImportError:
    from distutils.sysconfig import get_python_lib

    def _get_purelib():
        return get_python_lib(False)

def _uninstall():
    baseDir = _get_purelib()
    
    os.system("rm -rf %s" % (baseDir+'/cinder/volume/drivers/cas'))
    os.system("rm -rf %s" % (baseDir+'/kilo_cas_cinder*'))
    
    os.system("sed -i /openstack-cas-cinder-uninstall/d /usr/bin/openstack-cas-uninstall")
    if not os.path.getsize("/usr/bin/openstack-cas-uninstall"):
        os.system("rm -f /usr/bin/openstack-cas-uninstall")
    
    os.system("sed -i /kilo_cas_cinder/d /usr/bin/openstack-cas-version")
    if not os.path.getsize("/usr/bin/openstack-cas-version"):
        os.system("rm -f /usr/bin/openstack-cas-version")
    
    os.system("rm -f %s" % __file__)

if __name__ == "__main__":
    _uninstall()
