#CPU feature whitelist configuration file
#for example
#in x86 Arch
#source host cpu flags A,B,C; dest host cpu flags B,C,D;set src_feature_filter:A
#set(A,B,C) - set(B,C,D) - set(src_feature_filter) = {} meet the migration conditions
#in ARM arch
#source host cpu flags A,B,C; dest host cpu flags B,C,D;set src_feature_filter:A,set dest_feature_filter:D
#set(A,B,C) - set(src_feature_filter) = set(B,C,D) - set(dest_feature_filter) meet the migration conditions
src_feature_filter:sme sev sev_es csv csv2
dest_feature_filter:

#Host features mean that those CPU features will not pass through to the VM.
#for Intel
intel_host_feature_filter:dts acpi tm pbe art pebs bts nonstop_tsc aperfmperf dtes64 monitor ds_cpl smx est tm2 sdbg xtpr dca epb cat_l3 cat_l2 cdp_l3 intel_ppin cdp_l2 mba cqm rdt_a intel_pt xfd cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni dtherm ida pln pts hwp hwp_act_window hwp_epp hwp_pkg_req hfi tme bus_lock_detect enqcmd fsrm serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d pti
#for AMD
amd_host_feature_filter:constant_tsc nonstop_tsc aperfmperf monitor cmp_legacy extapic ibs skinit wdt tce topoext perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme mba sev sev_es cqm rdt_a cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local irperf rdpru amd_ppin lbrv svm_lock tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
#for Hygon
hygon_host_feature_filter:constant_tsc nonstop_tsc amd_dcm aperfmperf monitor extapic skinit wdt tce topoext perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate irperf lbrv svm_lock tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev sev_es
