#mem_max_percent means the max percentage of system memory that can be used as hugepage.
#like mem_max_percent, mem_recommend_percent means the recommend percentage.
#mem_max_percent and mem_max_percent must be a integer number, range in (1, 100).
mem_max_percent=75
mem_recommend_percent=50