#pci_sriov options

#This option allows CAS to set pci_sriov options(trust and spoofchk) when open SR-IOV.
#default is false, false means sriov_options in this file has no impact. aviable option is false/true
set_sriov_options = false

#This option sets SR-IOV virtual function(VF) as trusted, and allows the trusted VF to request selective promiscuous mode on the Physical function(PF).
#default is off, this means VF is not trusted. aviable option is off/on.
trust = off

#This option allows SR-IOV virtual function(VF) to transmit spoofed packets.
#default is on, this means VF will drop spoofed packets. aviable option is off/on.
spoofchk = on
