#

# logging level for each module, 
# must be one of the [DEBUG INFO WARNING ERROR CRITICAL], if not, use WARNING
# if module not exit, use WARNING level, 
# you can add one item, the format is "Logging_Level_xxx = DEBUG"
Logging_Level_br = WARNING
Logging_Level_cas_util = WARNING
Logging_Level_fc_san = WARNING
Logging_Level_ha = WARNING
Logging_Level_ovs = WARNING
Logging_Level_ocfs2 = WARNING
Logging_Level_ocfs2_fence = WARNING
Logging_Level_ocfs2_nvmf = WARNING
Logging_Level_sa = WARNING
Logging_Level_vncreflector = WARNING
Logging_Level_cas_alarm = WARNING
Logging_Level_cas_monitor = WARNING
Logging_Level_hostnetworkmonitor = WARNING
Logging_Level_device_config = DEBUG
Logging_Level_kernel_cmdline = DEBUG
Logging_Level_iommu_switch = DEBUG
Logging_Level_hugepage_config = DEBUG
Logging_Level_dumpPorts = DEBUG
Logging_Level_ovs_network_priority = DEBUG
Logging_Level_dpdkctl = DEBUG
Logging_Level_ovs_portmirror = DEBUG
Logging_Level_dnsmasq = INFO
Logging_Level_dpdk_pdump = DEBUG
Logging_Level_ovs_subnet = DEBUG
Logging_Level_inspection_ovs = INFO
Logging_Level_inspection_ha_init = INFO
Logging_Level_inspection_stor = WARNING
Logging_Level_isolate_mem = INFO
Logging_Level_memory_optimize = DEBUG
Logging_Level_set_performance_mode = INFO
