#!/bin/bash
set -x
OS_UOS=`cat /etc/os-release | grep 'uos'`
OS_Ubuntu=`cat /etc/os-release | grep 'ubuntu'`

case $1 in
    configure)
	
	ln -fs /opt/apps/com.manager.inode.arm/entries/applications/com.manager.inode.arm.desktop /usr/share/applications/com.manager.inode.arm.desktop
	
	if [ "$OS_Ubuntu" != "" ]
	then
		tar -zxvf /opt/apps/com.manager.inode.arm/files/lib64.tar.gz -C /opt/apps/com.manager.inode.arm/files/
		mv /usr/share/applications/com.manager.inode.arm.desktop /usr/share/applications/iNodeManager.desktop
	fi
	

        ;;
    *)
        ;;
esac

exit 0

