/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE TABLE TBL_UI_ITEM (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UI_NAME varchar(128) NOT NULL COMMENT '界面名称标识',
	COL_NAME varchar(128) NOT NULL COMMENT '列名称',
	COL_WIDTH int(10) NOT NULL COMMENT '缺省列宽',
	PRIMARY KEY (ID)
);

CREATE TABLE TBL_VM_WORKFLOW (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
  DOMAIN_ID BIGINT NOT NULL COMMENT '虚拟机ID',
  DOMAIN_NAME varchar(128) NOT NULL DEFAULT '' COMMENT '虚拟机名称',
  TITLE varchar(128) NOT NULL DEFAULT '',
  DESCRIPTION VARCHAR(254) COMMENT '虚拟机描述',
  USER_ID BIGINT NOT NULL COMMENT '用户ID',
  ORG_ID BIGINT NOT NULL COMMENT '组织ID',
  STATUS int(10) unsigned NOT NULL DEFAULT 0 COMMENT '状态（0待审批，10通过，11部署成功，12部署失败，20拒绝）',
  TYPE int(10) NOT NULL COMMENT '申请类型，1：申请虚拟机，0:注销虚拟机',
  CREATE_DATE DATETIME COMMENT '创建时间',
  HANDLE_DATE DATETIME NULL COMMENT '处理时间',
  APPLY_REASON VARCHAR(254) COMMENT '申请原因',
  HANDLE_REASON VARCHAR(512) COMMENT '处理意见',
  EXPIRE_DATE DATETIME NULL COMMENT '虚拟机到期日期',
  TEMPLATE_NAME varchar(128) COMMENT '模板名称',
  OS_VERSION VARCHAR(128),
  USER_NAME varchar(128) NOT NULL DEFAULT '' COMMENT '用户名称',
  HOST_NAME varchar(128) COMMENT '计算机名称',
  ADD_MODE int(10) COMMENT '隶属类型，1：域，0:工作组',
  GROUP_NAME varchar(128) COMMENT '域/工作组名称',
  LOGIN_NAME varchar(128) COMMENT '登录名称',
  LOGIN_PWD varchar(128) COMMENT '登录密码',
  CPU_CORES int(10) unsigned,
  CPU_SOCKETS int(10) unsigned,
  MEMORY int(10) unsigned,
  MEMORY_INIT double(10,2) COMMENT '分配的内存大小',
  MEMORY_UNIT VARCHAR(10) COMMENT '内存单位',
  ASSIGN_TYPE int(1) NOT NULL DEFAULT 0 COMMENT '分配类型, 0:DHCP 1:静态',
  IP varchar(64)  COMMENT 'IP地址',
  MASK varchar(64)  COMMENT '子网掩码',
  GATEWAY varchar(64)  COMMENT '默认网关',
  FIRST_DNS varchar(64) COMMENT '首选DNS服务器',
  SECOND_DNS varchar(64) COMMENT '备用DNS服务器',
  STORAGE int(10) unsigned,
  ANTIVIRUS_ENABLE INT(2) NOT NULL DEFAULT 0 COMMENT '是否安装防病毒',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_OPERATOR (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(256) NOT NULL,
  AUTH_TYPE SMALLINT NOT NULL DEFAULT 0,
  PASSWORD VARCHAR(256),
  USER_NAME VARCHAR(256),
  CREDENTIAL_NUMBER VARCHAR(256),
  EMAIL VARCHAR(256),
  ORGANIZATION VARCHAR(256),
  PHONE VARCHAR(256),
  ADDRESS VARCHAR(256),
  LAST_LOGIN_TIME DATETIME NULL,
  ENABLE int(10) DEFAULT '1' COMMENT '是否禁用：启用：1，禁用：0',
  LAST_MODIFY_PWD_TIME DATETIME COMMENT '最近一次修改密码时间',
  ACCESS_STRATEGY_ID BIGINT COMMENT '访问策略ID',
  ONLINE_NUM BIGINT,
  LDAP_SERVER_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_OPERATOR_PARAM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OPERATOR_ID BIGINT,
  NAME VARCHAR(256) NOT NULL,
  VALUE VARCHAR(256),
  PRIMARY KEY (ID),
  FOREIGN KEY (OPERATOR_ID) REFERENCES TBL_OPERATOR (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TBL_OP_GROUP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  CODE VARCHAR(256) NOT NULL,
  LEVEL int(10) NOT NULL,
  PARENT_ID BIGINT,  
  DESCRIPTION VARCHAR(512),
  FLAG int(10) unsigned NOT NULL DEFAULT '1' COMMENT '1: 可管理子分组, 0：不可管理子分组',
  MODE INT(10) DEFAULT 0,
  PRIMARY KEY(ID)
);

CREATE TABLE TBL_OPERATOR_OPGROUP (
  OPERATOR_ID BIGINT NOT NULL,
  OP_GROUP_ID BIGINT NOT NULL,
  FOREIGN KEY (OPERATOR_ID) REFERENCES TBL_OPERATOR (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY (OP_GROUP_ID) REFERENCES TBL_OP_GROUP (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TBL_OPGROUP_OPGROUP (
  PARENT_OP_GROUP_ID BIGINT NOT NULL,
  OP_GROUP_ID BIGINT NOT NULL,
  FOREIGN KEY (PARENT_OP_GROUP_ID) REFERENCES TBL_OP_GROUP (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY (OP_GROUP_ID) REFERENCES TBL_OP_GROUP (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TBL_OPERATOR_PERMISSION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OPERATOR_ID BIGINT,
  PERMISSION_ID VARCHAR(512) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (OPERATOR_ID ) REFERENCES TBL_OPERATOR (ID)
);

CREATE TABLE TBL_OPGROUP_PERMISSION (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OP_GROUP_ID BIGINT,
  PERMISSION_ID VARCHAR(512) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (OP_GROUP_ID) REFERENCES TBL_OP_GROUP (ID)
);

CREATE TABLE TBL_USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(256) NOT NULL,
  AUTH_TYPE SMALLINT NOT NULL DEFAULT 0,
  PASSWORD VARCHAR(256),
  USER_NAME VARCHAR(256),
  CREDENTIAL_NUMBER VARCHAR(256),
  EMAIL VARCHAR(256),
  ORGANIZATION VARCHAR(256),
  PHONE VARCHAR(256),
  ADDRESS VARCHAR(256),
  LAST_LOGIN_TIME DATETIME NULL,
  DEPT VARCHAR(256),
  POSITION VARCHAR(256),
  IMAGEURL VARCHAR(256),
  LDAP_SYNC_CONFIG_ID bigint(20) DEFAULT NULL,
  STATE int(10) NOT NULL DEFAULT '1' COMMENT '1：有效；0：无效',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_USER_GROUP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  CODE VARCHAR(256) NOT NULL,
  LEVEL int(10) NOT NULL,
  PARENT_ID BIGINT,
  ORG_ID BIGINT,
  DESCRIPTION VARCHAR(512),
  FLAG int(10) unsigned DEFAULT '0' COMMENT '1: 可管理子分组, 0：不可管理子分组',
  PRIMARY KEY(ID)
);

CREATE TABLE TBL_USER_USERGROUP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  USER_GROUP_ID BIGINT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES TBL_USER (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY (USER_GROUP_ID) REFERENCES TBL_USER_GROUP (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  PRIMARY KEY(ID)
);

CREATE TABLE TBL_USER_PARAM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT,
  NAME VARCHAR(256) NOT NULL,
  VALUE VARCHAR(512),
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES TBL_USER (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TBL_USER_OPERLOG (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  ORG_ID BIGINT, 
  LOGIN_NAME VARCHAR(256) NOT NULL,
  USER_NAME VARCHAR(256),
  OPER_TIME DATETIME NOT NULL,
  START_TIME DATETIME,
  END_TIME DATETIME,
  ADDRESS VARCHAR(256) NOT NULL,
  CATEGORY INT NOT NULL,
  TARGET_ID BIGINT,
  DESCRIPTION VARCHAR(512) NOT NULL,
  RESULT SMALLINT NOT NULL,
  FAILURE_REASON VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_HOSTPOOL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  PUBLIC_CLOUD_ID BIGINT,
  UNIQUE_KEY VARCHAR(64) NOT NULL DEFAULT '',
  FOREIGN_ID BIGINT,
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_CLUSTER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  HOST_POOL_ID BIGINT NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(256) ,
  ENABLE_HA int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0:不启用HA 1:启用HA',
  VM_RESTART_PRIORITY int(10) COMMENT '启动优先级:0:低级，1：中级，2：高级',
  ENABLE_LB int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0:不启用负载均衡 1:启用负载均衡',
  PERSIST_TIME int(10) COMMENT '持续时间', 
  CHECK_INTERVAL int(10) COMMENT '检查间隔',
  LB_MONITOR_ID BIGINT COMMENT '负载均衡监控策略ID',
  ENABLE_IPM int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0:不启用电源智能管理 1:启用电源智能管理',
  PERSIST_TIME_IPM int(10) COMMENT '持续时间', 
  IPM_LOWER_MONITOR_ID BIGINT COMMENT '主机回收监控策略ID',
  IPM_UPPER_MONITOR_ID BIGINT COMMENT '主机扩展监控策略ID',
  CHECK_INTERVAL_IPM int(10) COMMENT '检查间隔', 
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',  
  BROADCAST_ADDR VARCHAR(256) COMMENT '组播地址',
  BROADCAST_PORT int(10) COMMENT '组播端口',
  PUBLIC_CLOUD_ID BIGINT,
  UNIQUE_KEY VARCHAR(64) NOT NULL DEFAULT '',
  FOREIGN_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_HOST (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_ID BIGINT,
  NAME VARCHAR(256) NOT NULL COMMENT '主机名称',
  IPADDR VARCHAR(256) NOT NULL COMMENT '主机地址',
  HOST_USER varchar(45) NOT NULL DEFAULT 'root',
  PW varchar(45) DEFAULT NULL,
  MEMORY int(10) unsigned DEFAULT NULL ,
  CPU int(10) unsigned,
  CPU_CORES int(10) unsigned,
  CPU_SOCKETS int(10) unsigned,
  STORAGE bigint(20) unsigned DEFAULT NULL ,
  STATUS int(10) unsigned DEFAULT NULL ,
  CPU_FREQUENCY int(10) unsigned DEFAULT 0,
  CPU_PROVIDER varchar(45),
  CPU_DETAIL varchar(128),
  PROVIDER varchar(128),
  STORAGE_ALLOCATION bigint(20) unsigned ,
  STORAGE_AVILABLE bigint(20) unsigned ,
  ISCSI_NODE_NAME varchar(128),
  MAINTAIN int(10) unsigned DEFAULT 0 COMMENT '0:正常,1:维护模式',
  PUBLIC_CLOUD_ID BIGINT,
  UNIQUE_KEY VARCHAR(64) NOT NULL DEFAULT '',
  FOREIGN_ID BIGINT,
  MAC varchar(32),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',  
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_OPERLOG (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(256) NOT NULL,
  USER_NAME VARCHAR(256),
  OPER_TIME DATETIME NOT NULL,
  ADDRESS VARCHAR(256) NOT NULL,
  CATEGORY INT NOT NULL,
  DESCRIPTION VARCHAR(512) NOT NULL,
  RESULT SMALLINT NOT NULL,
  FAILURE_REASON VARCHAR(512),
  TARGET_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  OPER_OBJ VARCHAR(64) COMMENT '操作对象的主键',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_PARAMETER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TYPE VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  VALUE VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DOMAIN (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  HOST_ID int(10) unsigned DEFAULT '0',
  HOST_POOL_ID BIGINT,
  CLUSTER_ID BIGINT,
  DOMAIN_NAME varchar(128) NOT NULL DEFAULT '',
  TITLE varchar(128) NOT NULL DEFAULT '',
  DESCRIPTION VARCHAR(2048) ,
  STATUS varchar(32) DEFAULT 'shutOff' COMMENT 'running,paused,shutdown,shutOff',
  MEMORY int(10) unsigned NOT NULL DEFAULT '0' COMMENT '内存，兆',
  CPU int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'CPU个数',
  CDROM int(10) unsigned DEFAULT '0' COMMENT '0:CDROM 1:ISO',
  ENABLE int(10) unsigned DEFAULT '0' COMMENT '0:未管理;1:管理;2:模板',
  UUID varchar(60) NOT NULL DEFAULT '',
  OS_BIT varchar(45) DEFAULT '' COMMENT 'X86_64  X86_32',
  SYSTEM int(10) unsigned DEFAULT '0' COMMENT '0:Windows;1:Linux ',
  IMG_FILE_NAME varchar(256) DEFAULT NULL,
  IMG_FILE_TYPE varchar(45) DEFAULT 'NotDeployed' COMMENT '镜像文件类型，当cdrom值为0时，该值为host_cdrom',
  VIEW_TYPE varchar(45) DEFAULT NULL COMMENT '显示类型',
  AUTO int(10) unsigned DEFAULT '1' COMMENT '自动配置0：自动1：手动',
  DRIVE varchar(45) DEFAULT NULL COMMENT '显示驱动 vga;cirrus;vmvga',
  BOOTING_DEVICE int(10) unsigned DEFAULT '2' COMMENT '1 disk 2 cdrom',
  AUTO_BOOTING int(10) unsigned DEFAULT '0' COMMENT '0:不自动启动 1:自动启动',
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIORITY int(10) COMMENT '启动优先级',
  AUTO_MIGRATE TINYINT(2) COMMENT '是否允许自动迁移',
  ENABLE_VNC_PROXY int(10) DEFAULT 0 COMMENT '1：启用，0或空为不启用',
  CREATE_DATE DATETIME,
  PUBLIC_CLOUD_ID BIGINT,
  FOREIGN_ID BIGINT,
  COMPUTER_NAME varchar(128) COMMENT '计算机名称',
  OS_VERSION VARCHAR(128),
  MEMORY_INIT double(10,2) COMMENT '分配的内存大小',
  MEMORY_UNIT VARCHAR(10) COMMENT '内存单位',
  MEMORY_LOCKED int(10) unsigned COMMENT '内存预留',
  MEMORY_PRIORITY int(10) unsigned COMMENT '内存资源优先级',
  CPU_QUOTA_INIT INT(10) unsigned,
  CPU_QUOTA_UNIT VARCHAR(10),
  STORAGE_CAPACITY int(10),
  UNIQUE_KEY VARCHAR(64),
  CLOUD_TYPE int(2),
  ANTIVIRUS_ENABLE INT(2) NOT NULL DEFAULT 0 COMMENT '是否安装防病毒',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DOMAIN_CPU_DETAIL (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  TIME int(32) unsigned NOT NULL DEFAULT '0',
  CPU_RATE double DEFAULT NULL,
  MEMORY double DEFAULT NULL,
  DOMAIN_ID int(10) unsigned NOT NULL,
  HOST_ID int(10) unsigned,
  HOST_POOL_ID BIGINT,
  CLUSTER_ID int(10),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID),
  KEY `CPU_DETAIL_Index_2` (`TIME`,`DOMAIN_ID`,`OP_GROUP_CODE`)
);

CREATE TABLE TBL_DOMAIN_IO_STAT (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  TIME int(32) unsigned NOT NULL DEFAULT '0',
  DEV_NAME varchar(128) NOT NULL,
  IO_STAT double DEFAULT NULL,
  RD_STAT double DEFAULT NULL,
  WR_STAT double DEFAULT NULL,
  DOMAIN_ID int(10) unsigned NOT NULL,
  HOST_ID int(10) unsigned,
  HOST_POOL_ID BIGINT,
  CLUSTER_ID int(10),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID),
  KEY `IO_STAT_Index_1` (`TIME`,`DOMAIN_ID`,`OP_GROUP_CODE`)
);


CREATE TABLE TBL_DOMAIN_CPU_HOUR (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  DOMAIN_ID int(10) unsigned NOT NULL,
  HOST_ID int(10) unsigned,
  HOST_POOL_ID BIGINT,
  TIME int(32) unsigned NOT NULL DEFAULT '0',
  MEMORY int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY `CPU_HOUR_Index_2` (`DOMAIN_ID`,`TIME`)
);

CREATE TABLE TBL_DOMAIN_NETWORK (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  NET_TYPE int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0桥接 1NAT 2不使用网络',
  MAC varchar(60) DEFAULT NULL,
  IP_ADDR VARCHAR(256),
  DOMAIN_ID int(10) unsigned DEFAULT '0',
  NAME varchar(45) DEFAULT NULL COMMENT 'default ；bridgeNet ；空 ',
  DEVICE_MODEL varchar(45) NOT NULL DEFAULT 'rtl8139',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DOMAIN_STORAGE (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  STORE_FILE varchar(250) NOT NULL DEFAULT '',
  CAPACITY int(10) unsigned NOT NULL DEFAULT '0',
  DOMAIN_ID int(10) unsigned DEFAULT '0',
  TARGET_BUS varchar(10) NOT NULL DEFAULT '0' COMMENT 'ide scsi virtio usb\r\n\r\n    SCSI("scsi"),\r\n\r\n    VIRTIO("virtio"),\r\n\r\n    USB("usb");',
  TYPE  varchar(10) NOT NULL DEFAULT '0' COMMENT 'file block',
  DEVICE varchar(45) DEFAULT NULL COMMENT 'hda hdb hdc ',
  FORMAT varchar(45) DEFAULT NULL COMMENT 'Read-Write  Read-ForceWrite  Read-Only',
  DRIVE_TYPE varchar(10) DEFAULT NULL COMMENT '存储卷类型',
  ASSIGN_TYPE int(10) unsigned NOT NULL DEFAULT '0' COMMENT '0指定 1动态分配',
  DISK_DEVICE varchar(10),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_HOST_CPU_MEM_DETAIL (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  TIME BIGINT NOT NULL DEFAULT 0,
  CPU_RATE double,
  MEMORY_RATE double,
  HOST_ID BIGINT,
  HOST_POOL_ID BIGINT,
  CLUSTER_ID int(10),
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID),
  KEY `HOST_CPU_MEM_Index_2` (`TIME`,`HOST_ID`,`OP_GROUP_CODE`)
);

CREATE TABLE TBL_VSWITCH (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  CLUSTER_ID BIGINT,
  HOST_ID BIGINT,  
  DESCRIPTION VARCHAR(256),
  VNIC int(10) NOT NULL COMMENT '虚拟端口数量',
  MODE int(10) NOT NULL COMMENT '转发模式',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_VSWITCH_PNIC (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  VSWITCH_ID BIGINT,
  HOST_ID BIGINT NOT NULL,
  PNIC VARCHAR(256) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_VSWITCH_PORT_FLOW (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  TIME int(32) unsigned NOT NULL DEFAULT '0',
  RX_FLOW double DEFAULT NULL,
  RX_PACKETS double DEFAULT NULL,
  TX_FLOW double DEFAULT NULL,
  TX_PACKETS double DEFAULT NULL,
  VSWITCH_ID int(10) unsigned NOT NULL,
  VSWITCH_NAME varchar(256),
  VPORT VARCHAR(100) NOT NULL,
  DOMAIN_ID int(10) unsigned,
  DOMAIN_NAME varchar(128),
  MAC varchar(60) NULL,
  HOST_ID BIGINT NOT NULL,
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_ID BIGINT,
  PRIMARY KEY (ID),
  KEY `VSWITCH_PORT_FLOW_Index_1` (`VSWITCH_ID`,`VPORT`,`TIME`)
);

CREATE TABLE TBL_ORG (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL,
  DOMAIN_PRENAME VARCHAR(100) COMMENT '虚拟机名称前缀',
  DESCRIPTION VARCHAR(256),
  MAX_VM_NUM int(10), 
  ENABLE_ADJUST_SETTING int(10), 
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  BACKUP_DEST VARCHAR(256),
  MAX_CPU_NUM int(10) COMMENT 'CPU最大限制',
  MAX_MEM_NUM int(10) COMMENT '内存最大限制',
  MAX_STORAGE_NUM int(10) COMMENT '存储最大限制',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_OPERARTOR (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00', 
  OPERATOR_ID BIGINT,
  FLAG int(10) NOT NULL COMMENT '类型，1：操作员，2:操作员分组',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_COMPUTE_RES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  CLUSTER_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  FOREIGN_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_NET_RES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  CLUSTER_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  VSWITCH_NAME VARCHAR(256),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_STORAGE_RES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  CLUSTER_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  STORAGE_POOL_NAME VARCHAR(256),
  STORAGE_PATH VARCHAR(256),
  STORAGE_TYPE int(10) NOT NULL,
  ASSIGN_SIZE int(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_VM_TEMPLET (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  TEMPLET_ID BIGINT NOT NULL,
  DOMAIN_NAME VARCHAR(128),
  PUBLIC_CLOUD_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  USER_ID BIGINT,
  USER_GROUP_ID BIGINT,
  FLAG int(10) COMMENT '类型，1：租户，2:租户分组',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_FOLDER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  CLUSTER_ID BIGINT,
  STORAGE_POOL_NAME VARCHAR(256),
  STORAGE_PATH VARCHAR(256),
  FOLDER_NAME VARCHAR(256),
  FOLDER_PATH VARCHAR(256),
  CREATE_DATE TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ORG_PORT_PROFILE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  PROFILE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_USER_VM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT NOT NULL, 
  USER_ID BIGINT,
  USER_GROUP_ID BIGINT,
  DOMAIN_ID BIGINT NOT NULL,
  DESKTOP_POOL_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  RESOURCE_POOL_ID BIGINT NOT NULL,
  TITLE VARCHAR(128),
  FLAG int(10) COMMENT '类型，1：租户，2:租户分组',
  EXPIRE_DATE DATETIME NULL COMMENT '虚拟机到期日期',
  DISTRIBUTION_DATE DATETIME NULL COMMENT '虚拟机分配日期',
  UNIQUE_KEY VARCHAR(64),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DOMAIN_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DOMAIN_ID BIGINT NOT NULL,
  HOST_ID BIGINT NOT NULL,
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_ID BIGINT,
  TIME varchar(24) NOT NULL,
  MEMORY double(10,2) unsigned DEFAULT NULL,
  CPU double(10,2) unsigned DEFAULT NULL,  
  PRIMARY KEY (ID),
  KEY `DOMAIN_HOUR_STAT_Index_2` (`DOMAIN_ID`,`TIME`)
);

CREATE TABLE TBL_DOMAIN_FLOW_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TIME varchar(24) NOT NULL,
  RX_FLOW double DEFAULT NULL,
  TX_FLOW double DEFAULT NULL,
  DOMAIN_ID BIGINT,
  MAC varchar(60) NULL,
  HOST_ID BIGINT,
  HOST_POOL_ID BIGINT,
  CLUSTER_ID BIGINT,
  PRIMARY KEY (ID),
  KEY `DOMAIN_FLOW_HOUR_STAT_Index_1` (`DOMAIN_ID`,`TIME`)
);

CREATE TABLE TBL_DOMAIN_IO_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TIME varchar(24) NOT NULL,
  DEV_NAME varchar(128) NOT NULL,
  IO_STAT double DEFAULT NULL,
  RD_STAT double DEFAULT NULL,
  WR_STAT double DEFAULT NULL,
  DOMAIN_ID BIGINT NOT NULL,
  HOST_ID BIGINT NOT NULL,
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_ID BIGINT,
  PRIMARY KEY (ID),
  KEY `DOMAIN_IO_HOUR_STAT_Index_1` (`DOMAIN_ID`,`TIME`)
);

CREATE TABLE TBL_STAT_TASK (
  ID BIGINT NOT NULL AUTO_INCREMENT,  
  TASK_NAME varchar(128) NOT NULL,
  SRC_TABLE varchar(128) NOT NULL,
  DEST_TABLE varchar(128) NOT NULL,
  LAST_EXEC_TIME BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_PUBLIC_CLOUD (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL COMMENT '外部云名称',
  DESCRIPTION VARCHAR(254) COMMENT '外部云描述',
  FLAG SMALLINT NOT NULL COMMENT '外部云类型，1：阿里云, 2:CAS, 3 vmware',
  URI VARCHAR(128) COMMENT '访问外部云的URL或IP地址',  
  PROTOCAL VARCHAR(10) COMMENT '访问外部云的协议', 
  PORT SMALLINT COMMENT '访问外部云的Web端口', 
  USER_NAME VARCHAR(64) COMMENT '访问外部云的帐号',  
  PASSWORD VARCHAR(128) COMMENT '访问外部云的密码', 
  TENANT_ID VARCHAR(64) COMMENT 'cloudOS的租户或组织ID',
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',   
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DESKTOP_POOL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL COMMENT '虚拟桌面池名称',
  DESCRIPTION VARCHAR(254) COMMENT '虚拟桌面池描述',
  ASSIGN_MODE int(10) COMMENT '分配模式, 1,固定桌面池; 2,浮动桌面池',
  MAX_VM_NUM int(10), 
  ORG_ID BIGINT NOT NULL, 
  CLUSTER_ID BIGINT,
  RESOURCE_POOL_ID BIGINT,
  DOMAIN_ID BIGINT NOT NULL,
  STORAGE_POOL_NAME VARCHAR(256),
  STORAGE_PATH VARCHAR(256),
  STORAGE_TYPE int(10),
  COLOR_DEPTH int(10) COMMENT '颜色深度',
  REDIRECT_CLIPBOARD int(10) COMMENT '启用磁盘映射, 1 启用， 0 不启用',
  REDIRECT_DRIVES int(10) COMMENT '启用剪贴板映射',
  REDIRECT_PRINTERS int(10) COMMENT '启用打印机映射',
  REDIRECT_USB int(10) COMMENT '启用USB映射',
  REDIRECT_COMPORTS int(10) COMMENT '启用串口映射',
  AUDIO_MODE int(10) COMMENT '启用音频映射',
  START_IP VARCHAR(128),
  END_IP VARCHAR(128),
  IP_MASK VARCHAR(128),
  GATEWAY VARCHAR(128),
  FIRST_DNS varchar(64) COMMENT '首选DNS服务器',
  SECOND_DNS varchar(64) COMMENT '备用DNS服务器',
  USER_DATA VARCHAR(256),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_EVENT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CATALOG_ID INT NOT NULL,
  STATE INT NOT NULL,
  EVENT_LEVEL INT NOT NULL,
  EVENT_TYPE INT NOT NULL,
  EVENT_NAME VARCHAR(256),
  EVENT_SRC VARCHAR(256),
  EVENT_TIME DATETIME NOT NULL,
  EVENT_DESC VARCHAR(512) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_EVENT_CATALOG (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  EVENT_TYPE INT NOT NULL,
  REASON VARCHAR(1024),
  SUGGEST VARCHAR(1024),
  EXPERIENCE VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_HOST_NIC_FLOW (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  TIME int(32) unsigned NOT NULL DEFAULT '0',
  RX_FLOW double DEFAULT NULL,
  RX_PACKETS double DEFAULT NULL,
  TX_FLOW double DEFAULT NULL,
  TX_PACKETS double DEFAULT NULL,
  MAC varchar(60) NULL,
  HOST_ID BIGINT NOT NULL,
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_ID BIGINT,
  PRIMARY KEY (ID),
  KEY `TBL_HOST_NIC_FLOW_Index_1` (`HOST_ID`,`TIME`)
);

CREATE TABLE TBL_DOMAIN_FLOW_LINK_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TIME varchar(24) NOT NULL,
  FLOW_LINK int(10) unsigned DEFAULT NULL,
  DOMAIN_ID BIGINT,
  HOST_ID BIGINT,
  HOST_POOL_ID BIGINT,
  CLUSTER_ID BIGINT,
  PRIMARY KEY (ID),
  KEY `TBL_DOMAIN_FLOW_LINK_STAT_Index_1` (`DOMAIN_ID`,`TIME`)
);

CREATE TABLE TBL_VAPP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TREE_CODE VARCHAR(256) NOT NULL,
  FOLDER_NAME varchar(60)  NOT NULL,
  FOLDER_LEVEL int(10) unsigned,
  PARENT_ID BIGINT,
  OPERATOR_ID BIGINT,
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID),
  KEY `VAPP_Index_1` (`OPERATOR_ID`)
);

CREATE TABLE TBL_VAPP_DOMAIN (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FAVORITE_ID BIGINT NOT NULL,
  DOMAIN_ID BIGINT,
  PUBLIC_CLOUD_ID BIGINT,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_PREREGISTER_USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(256) NOT NULL,
  PASSWORD VARCHAR(256),
  USER_NAME VARCHAR(256),
  CREDENTIAL_NUMBER VARCHAR(256),
  EMAIL VARCHAR(256),
  PHONE VARCHAR(256),
  ADDRESS VARCHAR(256),
  DEPT VARCHAR(256),
  POSITION VARCHAR(256),
  STATE int(10),
  HANDLE_REASON VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_VM_APPEND_DEFINE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  COLUMN_NAME VARCHAR(64) NOT NULL,
  FIELD_NAME VARCHAR(64) NOT NULL,
  FIELD_TYPE int(10) unsigned NOT NULL,
  FIELD_ALLOW_BLANK int(10) unsigned NOT NULL,
  FIELD_MAX int(10),
  FIELD_MIN int(10),
  FIELD_LEN int(10),
  DEFAULT_VALUE VARCHAR(256),
  FIELD_PRIORITY int(10),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_VM_APPEND_DEFINE_OPTIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEFINE_ID BIGINT NOT NULL,
  FIELD_OPTIONS VARCHAR(128) NOT NULL,  
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_VM_WORKFLOW_APPEND (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  VM_WORKFLOW_ID BIGINT NOT NULL,
  COLUMN_01 VARCHAR(256),
  COLUMN_02 VARCHAR(256),
  COLUMN_03 VARCHAR(256),
  COLUMN_04 VARCHAR(256),
  COLUMN_05 VARCHAR(256),
  COLUMN_06 VARCHAR(256),
  COLUMN_07 VARCHAR(256),
  COLUMN_08 VARCHAR(256),
  COLUMN_09 VARCHAR(256),
  COLUMN_10 VARCHAR(256),
  COLUMN_11 VARCHAR(256),
  COLUMN_12 VARCHAR(256),
  COLUMN_13 VARCHAR(256),
  COLUMN_14 VARCHAR(256),
  COLUMN_15 VARCHAR(256),
  COLUMN_16 VARCHAR(256),
  COLUMN_17 VARCHAR(256),
  COLUMN_18 VARCHAR(256),
  COLUMN_19 VARCHAR(256),
  COLUMN_20 VARCHAR(256),
  COLUMN_21 VARCHAR(256),
  COLUMN_22 VARCHAR(256),
  COLUMN_23 VARCHAR(256),
  COLUMN_24 VARCHAR(256),
  COLUMN_25 VARCHAR(256),
  COLUMN_26 VARCHAR(256),
  COLUMN_27 VARCHAR(256),
  COLUMN_28 VARCHAR(256),
  COLUMN_29 VARCHAR(256),
  COLUMN_30 VARCHAR(256),
  COLUMN_31 VARCHAR(256),
  COLUMN_32 VARCHAR(256),
  COLUMN_33 VARCHAR(256),
  COLUMN_34 VARCHAR(256),
  COLUMN_35 VARCHAR(256),
  COLUMN_36 VARCHAR(256),
  COLUMN_37 VARCHAR(256),
  COLUMN_38 VARCHAR(256),
  COLUMN_39 VARCHAR(256),
  COLUMN_40 VARCHAR(256),
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_APPLYDISK(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(128),
   USER_ID BIGINT NOT NULL,
   HOST_ID BIGINT,
   DOMAIN_ID BIGINT,
   PATH VARCHAR(512),
   STATE INT(10) unsigned NOT NULL DEFAULT 0 COMMENT '0待审批 1审批通过 2 驳回',
   CAPACITY INT(10) unsigned COMMENT '容量',
   HANDLE_REASON VARCHAR(512) COMMENT '处理意见',
   CREATE_DATE datetime,
   HANDLE_DATE datetime,
   ORG_ID BIGINT NOT NULL,
   PRIMARY KEY (ID)
);


CREATE TABLE TBL_CLOUD_MESSAGE(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 TITLE VARCHAR(256),
 CONTENT VARCHAR(1024),
 MSG_LEVEL INT(1) COMMENT '1：一般消息 2：重要消息',
 FROM_OPERATOR_ID BIGINT NOT NULL,
 DELETE_FLAG INT(1) COMMENT '0未删除 1：操作员删除 ',
 CREATE_TIME DATETIME COMMENT '创建时间',
 PRIMARY KEY(ID)
);

CREATE TABLE TBL_USER_MESSAGE(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 MSG_ID BIGINT NOT NULL,
 USER_ID BIGINT,
 USER_GROUP_ID BIGINT,
 ORG_ID BIGINT NOT NULL,
 FLAG INT(1) COMMENT '类型，1：租户，2:租户分组',
 IS_READ INT(1) DEFAULT 0 COMMENT '是否已读 1：已读，0：未读',
 PRIMARY KEY(ID)
);

CREATE TABLE TBL_CLOUD_WORK_ORDER(
 ID BIGINT NOT NULL AUTO_INCREMENT,
 TITLE VARCHAR(256),
 CONTENT VARCHAR(1024),
 FROM_USER_ID BIGINT NOT NULL,
 REPLY VARCHAR(1024),
 FROM_OPERATOR_ID BIGINT,
 STATUS INT(1) COMMENT '1:未回复  2:已回复',
 CREATE_TIME DATETIME COMMENT '创建时间',
 REPLY_TIME  DATETIME COMMENT '回复时间',
 DESTROY_TYPE INT(1) COMMENT '1:用户删除  2:管理员删除',
 ORG_ID BIGINT NOT NULL,
 PRIMARY KEY(ID)
);

CREATE TABLE TBL_BACKUP_HISTORY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(128),
  DESCRIPTION VARCHAR(254),
  CREATE_TIME DATETIME COMMENT '创建时间',
  USER_ID BIGINT NOT NULL,
  DOMAIN_ID BIGINT NOT NULL,
  DOMAIN_NAME VARCHAR(128),
  PATH VARCHAR(128) NOT NULL COMMENT '备份的绝对路径',
  PRIMARY KEY (ID)

);

CREATE TABLE TBL_ACCESS_STRATEGY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL COMMENT '访问策略名称',
  DESCRIPTION VARCHAR(256) COMMENT '访问策略描述',
  DEFAULT_ACCESS_ACTION int(10) COMMENT '访问规则默认动作(0:拒绝;1:允许)',
  CREATE_TIME DATETIME COMMENT '访问策略创建时间',
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  FREQUENCY int(10) DEFAULT 0 COMMENT '频率:，0：不启用:1：每周，2：每天 ',
  DATE_START int(10),
  DATE_END int(10),
  ACCTIMER varchar(256) COMMENT '时间点',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ACCESS_RULE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ACCESS_STRATEGY_ID int(10) NOT NULL,
  START_IP VARCHAR(64) COMMENT '源IP地址',
  END_IP VARCHAR(64) COMMENT '目的IP地址',
  ACCESS_ACTION  int(10) COMMENT '访问规则动作(0:拒绝;1:允许)',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_LDAP_SYNC_CONFIG (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SYNC_CONFIG_NAME varchar(256) NOT NULL,
  LDAP_SERVER_ID BIGINT DEFAULT NULL,
  STATE int(10) NOT NULL DEFAULT '0' COMMENT '0:无效;1:有效',
  AUTO_SYNC int(10) DEFAULT '0' COMMENT '0:否;1:自动同步',
  SYNC_NEW_USER int(10) DEFAULT '0' COMMENT '0:否;1:是',
  SYNC_EXIST_USER int(10) DEFAULT '0' COMMENT '0:否;1:是',
  SYNC_ACCORDING_NEED int(10) DEFAULT '0' COMMENT '0:否;1:是',
  SYNC_ONLY_CURRENT_NODE int(10) DEFAULT '0' COMMENT '0:否;1:是',
  SUB_BASE_DN varchar(256),
  FILTER varchar(256),
  ORG_ID BIGINT NOT NULL,
  SYNC_USER_GROUP int(10) DEFAULT '0' COMMENT '0:不同步用户分组;1:按OU同步;2:按group同步',
  USER_GROUP_ID BIGINT DEFAULT NULL,
  LOGIN_NAME varchar(256),
  PASSWORD varchar(256),
  USER_NAME varchar(256),
  CREDENTIAL_NUMBER varchar(256) DEFAULT NULL,
  ADDRESS varchar(256) DEFAULT NULL,
  PHONE varchar(256) DEFAULT NULL,
  EMAIL varchar(256),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE varchar(256) DEFAULT '00',
  SYNC_AUTO_DELETE_USER int(10) DEFAULT '0' COMMENT '0:否;1:是',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_LDAP_SERVER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME varchar(256) NOT NULL,
  VERSION varchar(10) NOT NULL,
  IP_ADDR varchar(64) NOT NULL,
  PORT int(10) unsigned NOT NULL,
  SERVER_TYPE int(10) NOT NULL COMMENT '2:微软活动目录;1:通用LDAP服务器',
  SYNC_TYPE int(10) COMMENT '1:手工指定;2:基于Group同步',
  CONNECTE_TIMEOUT int(10) unsigned DEFAULT NULL,
  SYNC_TIEMOUT int(10) unsigned DEFAULT NULL,
  PAGING_SYNC_USER int(10) DEFAULT '0' COMMENT '1:PAGING;0:NOT PAGING',
  BASE_DN varchar(256) NOT NULL,
  ADMIN_DN varchar(256) NOT NULL,
  ADMIN_PWD varchar(64) NOT NULL,
  USER_NAME_ATTR varchar(256),
  USER_PASSWD_ATTR varchar(256),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE varchar(256) DEFAULT '00',
  CUT_USER_ATTR_PREFIX int(10) DEFAULT '0' COMMENT '截取用户名属性前缀标志，0为不截取，1为截取',
  CUT_USER_ATTR_SUFFIX int(10) DEFAULT '0' COMMENT '截取用户名属性后缀标志，0为不截取，1为截取',
  PREFIX_SEPARATOR varchar(20) DEFAULT NULL,
  SUFFIX_SEPARATOR varchar(20) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_DESKTOP_POOL_USER_GROUP(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DESKTOP_POOL_ID BIGINT,
	USER_GROUP_ID BIGINT,
	PRIMARY KEY (ID)
);

CREATE TABLE TBL_RETRIEVE_STRATEGY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STATE int(10) COMMENT '是否生效：生效：1，不生效：0', 
  ACTION int(10) COMMENT '回收动作：关闭：0，启动：1，回收：2',
  FREQUENCY int(10) COMMENT '频率:，0：每年:1：每月，2：每周：3 每天：4 ',
  MONTH int(10),
  MONTH_END int(10),
  DAY int(10) COMMENT '哪天：几日，或星期几，每天 ',
  DAY_END int(10) COMMENT '哪天：几日，或星期几，每天 ',
  DESKTOP_POOL_ID BIGINT,
  RETRIEVE_TIME varchar(256),
  PRIMARY KEY (ID)
);

-- 云备份策略
CREATE TABLE TBL_CLOUD_BACKUP_STRATEGY (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  DESCRIPTION varchar(256) DEFAULT NULL,
  FREQUENCY int(2) NOT NULL,
  DAY varchar(128) DEFAULT NULL,
  HOUR int(3) NOT NULL,
  USER_ID bigint(10) NOT NULL,
  ORG_ID bigint(10) NOT NULL,
  STATE int(2) NOT NULL,
  KEEP_NUMBER int(2) DEFAULT NULL,
  AUTO_REPLACEMENT int(2) DEFAULT '1' COMMENT '0:不自动替换旧备份 1:自动替换旧备份',
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 云备份策略电子流
CREATE TABLE TBL_CLOUD_BACKUP_STRATEGY_WORKFLOW (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  NAME varchar(128) NOT NULL,
  DESCRIPTION varchar(256) DEFAULT NULL,
  FREQUENCY int(2) NOT NULL,
  DAY varchar(128) DEFAULT NULL,
  HOUR int(3) NOT NULL,
  USER_ID bigint(10) NOT NULL,
  ORG_ID bigint(10) NOT NULL,
  KEEP_NUMBER int(2) DEFAULT NULL,
  AUTO_REPLACEMENT int(2) DEFAULT '1' COMMENT '0:不自动替换旧备份 1:自动替换旧备份',
  VERIFY_STATE int(2) NOT NULL,
  SUGGESTION varchar(256) DEFAULT NULL,
  CREATE_DATE datetime,
  HANDLE_DATE datetime,
  STRATEGY_ID bigint(10) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 云备份策略虚拟机
CREATE TABLE TBL_CLOUD_BACKUP_VM (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  STRATEGY_ID bigint(10) NOT NULL,
  DOMAIN_ID bigint(10) NOT NULL,
  ORG_ID  bigint(10) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 云备份策略电子流虚拟机
CREATE TABLE TBL_CLOUD_BACKUP_WORKFLOW_VM (
  ID bigint(10) NOT NULL AUTO_INCREMENT,
  STRATEGY_WORKFLOW_ID bigint(10) NOT NULL,
  DOMAIN_ID bigint(10) NOT NULL,
  ORG_ID  bigint(10) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 用户告警策略表
CREATE TABLE TBL_EVENT_STRATEGY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME varchar(128),
  DESCRIPTION varchar(256) DEFAULT NULL,
  STATE int(2) NOT NULL,
  USER_ID bigint(10) NOT NULL,
  PRIMARY KEY (ID)
);

-- 告警策略与虚拟机关系表
CREATE TABLE TBL_EVENT_STRATEGY_DOMAIN(
  	ID BIGINT NOT NULL AUTO_INCREMENT,
  	EVENT_STRATEGY_ID int(10) NOT NULL COMMENT '用户设置的告警策略的ID',
    DOMAIN_ID bigint(10) NOT NULL,
    ORG_ID BIGINT(10) NOT NULL,
	PUBLIC_CLOUD_ID BIGINT,
	BASE_EVENT_ID BIGINT DEFAULT 0 COMMENT '基准告警ID',
    LAST_EVENT_ID BIGINT DEFAULT 0 COMMENT '最后发送的告警ID',
    BASE_EVENT_TIME DATETIME COMMENT '基准告警时间',
    LAST_EVENT_TIME DATETIME COMMENT '最后发送的告警时间',
    PRIMARY KEY (ID)
);

-- 流程定制表
CREATE TABLE TBL_WORKFLOW(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	NAME varchar(128) NOT NULL DEFAULT '' COMMENT '流程名称',
	DESCRIPTION VARCHAR(254) COMMENT '流程描述',
	PRIMARY KEY (ID)
);

-- 流程定制步骤表
CREATE TABLE TBL_WORKFLOW_STEP(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	TYPE int(10) NOT NULL COMMENT '审批类型，1:单签，2:会签，3：选签，4:半数签',
	LEVEL int(10) COMMENT '审批级别',
	PARENT_ID BIGINT COMMENT '上一步的步骤ID',
	WORKFLOW_ID BIGINT NOT NULL COMMENT '流程定制ID',
	VERSION int(10) COMMENT '流程版本',
	PRIMARY KEY (ID)
);

-- 流程定制步骤与操作员-关系表
CREATE TABLE TBL_WORKFLOW_STEP_OP(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	WORKFLOW_ID BIGINT NOT NULL COMMENT '流程定制ID',
	WORKFLOW_STEP_ID BIGINT NOT NULL COMMENT '流程定制步骤ID',
	OP_ID BIGINT COMMENT '操作员ID',
	OP_TYPE BIGINT(20) DEFAULT 0,
	PRIMARY KEY (ID)
);

-- 审批记录表
CREATE TABLE TBL_APPROVAL_RECORD(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	TYPE int(10) NOT NULL COMMENT '电子流类型，1:申请虚拟机，2:申请云硬盘，3：用户预注册，4:申请云备份策略',
	HANDLE_RESULT int(10) unsigned COMMENT '状态（1:同意，2:驳回，3:转签）',
	STATUS int(10) DEFAULT 1 COMMENT '状态（1:有效，0:失效）',
  	HANDLE_REASON VARCHAR(512) COMMENT '处理意见',
  	HANDLE_DATE DATETIME NULL COMMENT '处理时间',
  	APPLY_RECORD_ID BIGINT COMMENT '原始申请记录ID',
  	OP_ID BIGINT COMMENT '操作员ID',
  	HANDLE_OP_ID BIGINT COMMENT '处理操作员ID',
  	WORKFLOW_ID BIGINT NOT NULL COMMENT '流程定制ID',
	WORKFLOW_STEP_ID BIGINT NOT NULL COMMENT '流程定制步骤ID',
	APPROVAL_TYPE int(10) NOT NULL COMMENT '审批类型，1:单签，2:会签，3：选签，4:半数签',
	ENTRUST_OP_ID BIGINT COMMENT '转审操作员ID',
	VERSION int(10) COMMENT '流程版本',
	REMINDER_SIGN_DATE DATETIME NULL COMMENT '催签时间',
	HANDLE_OP_USER_NAME VARCHAR(512),
	PRIMARY KEY (ID)
);

-- 操作员委托表
CREATE TABLE TBL_OP_ENTRUST(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	OP_ID BIGINT COMMENT '委托操作员ID',
	ENTRUST_OP_ID BIGINT COMMENT '被委托操作员ID',
	TYPE int(10) COMMENT '业务ID：0 全委托、1 虚拟机电子流、2 云硬盘电子流、3 用户预注册、4 云备份策略',
	PRIMARY KEY (ID)
);

-- 操作员委托历史表
CREATE TABLE TBL_OP_ENTRUST_HISTORY(
	ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '物理ID',
	OP_ID BIGINT COMMENT '委托操作员ID',
	ENTRUST_OP_ID BIGINT COMMENT '被委托操作员ID',
	TYPE int(10) COMMENT '业务ID：0 全委托、1 虚拟机电子流、2 云硬盘电子流、3 用户预注册、4 云备份策略',
	STARTTIME DATETIME COMMENT '委托时间',
	ENDTIME DATETIME COMMENT '撤销委托时间',
	PRIMARY KEY (ID)
);

CREATE TABLE TBL_BACKUP_CIC_STRATEGY (
  ID INT(10) NOT NULL,
  STATE int(10) COMMENT '是否生效：生效：1，不生效：0',
  STORE_MODE int(10) COMMENT '备份目的类型，0：本地，1：远端服务器',
  STORE_LOCATION VARCHAR(256) COMMENT '备份文件位置',
  TARGET_ADDR VARCHAR(256) COMMENT '目的服务器IP地址', 
  LOGIN_NAME VARCHAR(50) COMMENT '目的服务器用户名', 
  PASSWORD VARCHAR(50)  COMMENT '密码', 
  SERVER_TYPE int(10) COMMENT '服务器类型，0：选择FTP，1:选择SCP',
  PORT int(10) COMMENT '服务器类型端口',
  FREQUENCY int(10) COMMENT '频率:，0：每月:1：每周，2：每日 ',
  DAY int(10) COMMENT '哪天：几日，或星期几，每天 ',
  HOUR int(10) COMMENT '时',
  MINUTES int(10) COMMENT '分', 
  NEXT_BACKUP DATETIME COMMENT '下一次备份时间',
  KEEP_TIMES int(10) COMMENT '备份文件保留数量',
  ISRUNNING int(10) COMMENT '备份任务是否正在执行，1：正在执行，0未运行。',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_BACKUP_HISTORY_INFO (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FILE_NAME VARCHAR(128),
    CREATE_TIME VARCHAR(128),
    VERSION VARCHAR(128),
    BACKUP_LOCATION VARCHAR(256) COMMENT '备份文件位置',
	STORE_MODE int(10) COMMENT '备份目的类型，0：本地，1：远端服务器',
	SERVER_TYPE int(10) COMMENT '服务器类型，0：选择FTP，1:选择SCP',
	PORT int(10) COMMENT '服务器类型端口',
	TARGET_ADDR VARCHAR(256) COMMENT '目的服务器IP地址', 
	LOGIN_NAME VARCHAR(50) COMMENT '目的服务器用户名', 
    PASSWORD VARCHAR(50)  COMMENT '密码',
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_ANTIVIRUS_SOFTWARE (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  VENDOR int(4) NOT NULL DEFAULT 0,
  VERSION varchar(128),
  FILE_PATH varchar(256),
  FILE_NAME varchar(128),
  UPLOAD_STATUS int(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
) ;

CREATE TABLE TBL_ACL_STRATEGY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(256) NOT NULL COMMENT 'ACL策略名称',
  TYPE INT NOT NULL DEFAULT 3 COMMENT 'acl策略类型，3表示三层/四层ACL，2表示二层ACL',
  DESCRIPTION VARCHAR(256) COMMENT 'ACL策略描述',
  DEFAULT_ACL_ACTION int(10) COMMENT 'ACL规则入方向默认动作(0:拒绝;1:允许)',
  DEFAULT_ACL_OUT_ACTION int(10) COMMENT 'ACL规则出方向默认动作(0:拒绝;1:允许)',
  CREATE_TIME DATETIME COMMENT 'ACL策略创建时间',
  LAST_UPDATE_TIME INT(11) NULL DEFAULT 0 COMMENT 'ACL策略最后更新时间',
  EFFECT_TIME_RANGE VARCHAR(256) NULL COMMENT '二层ACL策略生效时间段,如：0-3,5-5',
  TIMERANGE_ENABLED INT(2) DEFAULT 0 COMMENT '时间段配置是否生效，0不生效 1生效',
  UUID varchar(64),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ACL_RULE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ACL_STRATEGY_ID int(10) NOT NULL,
  PROTOCOL int(10) COMMENT 'ACL规则协议号码, ICMP为1,TCP为6,UDP为17，所有协议为65535',
  SRC_IP VARCHAR(64) COMMENT '源IP地址',
  SRC_MASK VARCHAR(64) COMMENT '源IP掩码',
  SRC_PORT int(10) COMMENT '源端口',
  DEST_IP VARCHAR(64) COMMENT '目的IP地址',
  DEST_MASK VARCHAR(64) COMMENT '目的IP掩码',
  DEST_PORT int(10) COMMENT '目的端口',
  SRC_MAC VARCHAR(64) NULL COMMENT '二层ACLRule中使用的源MAC',
  DEST_MAC VARCHAR(64) NULL COMMENT '二层ACLRule中使用的目的MAC',
  ACTION  int(10) COMMENT 'ACL规则对报文采取的动作(0:拒绝;1:允许)',
  PRIORITY int(10) COMMENT '优先级',
  DIRECTION int(10) COMMENT '被ACL所控制报文的流向，此字段目前前台不显示，0表示流入；1，表示流出。默认为1。',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ACLSTRATEGY_PUBLICCLOUD (
  ACLSTRATEGY_ID BIGINT NOT NULL,
  PUBLICCLOUD_ID BIGINT NOT NULL,
  FOREIGN KEY (ACLSTRATEGY_ID) REFERENCES TBL_ACL_STRATEGY (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
  FOREIGN KEY (PUBLICCLOUD_ID) REFERENCES TBL_PUBLIC_CLOUD (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE TBL_COMPUTE_ZONE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  UNIQUE_KEY VARCHAR(64) NOT NULL,
  PUBLIC_CLOUD_ID BIGINT NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ALARM_RULE (
  ID  bigint(20) NOT NULL AUTO_INCREMENT ,
  RULE_NAME  varchar(256) NOT NULL ,
  CATEGORY  int(10) NOT NULL DEFAULT 6 COMMENT '告警大类，默认6-其他类' ,
  ORDER_ID  int(10) NOT NULL DEFAULT 100 COMMENT '用于告警界面排序' ,
  TYPE  int(10) NOT NULL DEFAULT 0 COMMENT '告警类型' ,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ALARM_NOTICE_TEMPLATE (
  ID  bigint(20) NOT NULL AUTO_INCREMENT,
  NAME  varchar(256) NOT NULL ,
  DESCRIPTION  varchar(256) NULL ,
  SEND_TYPE  int(2) NOT NULL DEFAULT 0 COMMENT '通知方式,0:邮件；1:短信' ,
  ALARM_LEVEL  int(2) NOT NULL DEFAULT 12 COMMENT '告警级别，默认:紧急，重要' ,
  SELECTED_RULE_TYPE  int(2) NOT NULL DEFAULT 0 COMMENT '0:所有告警；1:选定告警' ,     
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00', 
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ALARM_NOTICE_TEMPLATE_ADDRESS (
  ID  bigint(20) NOT NULL AUTO_INCREMENT ,
  TEMPLATE_ID  bigint(20) NOT NULL ,
  ADDRESS  varchar(255) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_ALARM_NOTICE_TEMPLATE_RULE (
  ID  bigint(20) NOT NULL AUTO_INCREMENT ,
  TEMPLATE_ID  bigint(20) NOT NULL ,
  RULE_ID  bigint(20) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE TBL_PUBCLOUD_ALARM_CONFIG (
  ID  bigint(20) NOT NULL AUTO_INCREMENT ,
  PUBLIC_CLOUD_ID  bigint(20) NOT NULL ,
  EMAIL_TEMPLATE_ID  bigint(20) NULL ,
  MESSAGE_TEMPLATE_ID  bigint(20) NULL ,
  PRIMARY KEY (ID)
);


CREATE TABLE TBL_PUBCLOUD_ALARM_MONITORED_RES (
  ID  bigint(20) NOT NULL AUTO_INCREMENT ,
  CONFIG_ID  bigint(20) NOT NULL ,
  SEND_TYPE  int(2) NOT NULL DEFAULT 0 COMMENT '类型，0：邮件；1：短信；' ,
  UNIQUE_KEY  VARCHAR(64) NOT NULL ,
  RESOURCE_TYPE  int(2) NOT NULL DEFAULT 0 COMMENT '指标类型，0：主机；1：虚拟机' ,
  PRIMARY KEY (ID)
);

-- 组织资源池关系
CREATE TABLE TBL_ORG_RESOURCE_POOL (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   ORG_ID BIGINT NOT NULL,
   RESOURCE_POOL_ID BIGINT NOT NULL,
   PRIMARY KEY (ID)
);
-- 资源池
CREATE TABLE TBL_RESOURCE_POOL (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(128) NOT NULL COMMENT '资源池名称',
	DESCRIPTION VARCHAR(256)  COMMENT '资源池描述',
	CLOUD_ID BIGINT COMMENT '云资源ID',	
	CLOUD_TYPE INT COMMENT '云资源类型',
	CLOUD_NAME VARCHAR(128) NOT NULL COMMENT '云资源名称',
	USE_LOCAL_STORAGE_FLAG INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '1 允许使用本地存储, 0 不允许是引用本地存储',
	OP_GROUP_ID BIGINT DEFAULT 1,
  	OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
	PRIMARY KEY (ID)
);
-- 资源池集群关系
CREATE TABLE TBL_RESOURCE_POOL_CLUSTER (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CLUSTER_NAME VARCHAR(128) NOT NULL COMMENT '集群名称',
    RESOURCE_POOL_ID BIGINT NOT NULL COMMENT '资源池ID',
    CLUSTER_ID BIGINT NOT NULL COMMENT '集群ID',	
    CLOUD_ID BIGINT COMMENT '云资源ID',	
	UNIQUE_KEY VARCHAR(64) COMMENT '云资源端的集群唯一标识符',
	PRIMARY KEY (ID)
);
-- 资源池网络关系
CREATE TABLE TBL_RESOURCE_POOL_NET (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(128) NOT NULL COMMENT '网络名称',
    RESOURCE_POOL_ID BIGINT NOT NULL COMMENT '资源池ID',
    CLOUD_ID BIGINT COMMENT '云资源ID',	
	PRIMARY KEY (ID)
);
-- 资源池网络策略模板关系
CREATE TABLE TBL_RESOURCE_POOL_PROFILE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(128) NOT NULL COMMENT '网络策略模板名称',
    RESOURCE_POOL_ID BIGINT NOT NULL COMMENT '资源池名称',
    CLOUD_ID BIGINT COMMENT '云资源ID',	
	PRIMARY KEY (ID)
);
-- 资源池存储关系
CREATE TABLE TBL_RESOURCE_POOL_STORAGE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(256) NOT NULL COMMENT '存储池名称',
    RESOURCE_POOL_ID BIGINT NOT NULL COMMENT '资源池ID',
    CLOUD_ID BIGINT COMMENT '云资源ID',
    PATH VARCHAR(256) NOT NULL COMMENT '路经',
    TYPE INT (10) COMMENT '类型',
	BACKUP_FLAG INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '1 作为备份存储, 0 不作为备份存储',
	PRIMARY KEY (ID)
);

-- 主机cpu内存报表
CREATE TABLE TBL_HOST_PREF_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  HOST_POOL_ID BIGINT NOT NULL,
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  TIME varchar(24) NOT NULL,
  MEMORY double(10,2) unsigned DEFAULT NULL,
  CPU double(10,2) unsigned DEFAULT NULL,  
  MEMORY_MAX double(10,2),
  MEMORY_MIN double(10,2),
  CPU_MAX double(10,2),
  CPU_MIN double(10,2),
  PRIMARY KEY (ID)
);
-- 主机网络报表
CREATE TABLE TBL_HOST_NIC_FLOW_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  TIME varchar(24) NOT NULL,
  RX_FLOW double DEFAULT NULL,
  TX_FLOW double DEFAULT NULL,
  MAC varchar(60) NULL,
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  HOST_POOL_ID BIGINT,
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  RX_FLOW_AVG double(10,2),
  RX_FLOW_MAX double(10,2),
  RX_FLOW_MIN double(10,2),
  TX_FLOW_AVG double(10,2),
  TX_FLOW_MAX double(10,2),
  TX_FLOW_MIN double(10,2),
  PRIMARY KEY (ID)
);

-- 主机磁盘IO报表
CREATE TABLE TBL_HOST_IO_HOUR_STAT(
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  TIME varchar(24) NOT NULL,
  DEV_NAME varchar(128) NOT NULL,
  IO_STAT double,
  RD_STAT double,
  WR_STAT double,
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  HOST_POOL_ID bigint(20) NOT NULL,
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  RD_STAT_MAX double(10,2),
  RD_STAT_MIN double(10,2),
  WR_STAT_MAX double(10,2),
  WR_STAT_MIN double(10,2),
  UTILIZATION double default 0,
  UTILIZATION_MAX double default 0,
  UTILIZATION_MIN double default 0,
  PRIMARY KEY (ID)
);

-- 自定义监控
CREATE TABLE TBL_DEFINED_MONITOR (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NODE_NAME VARCHAR(256) NOT NULL,
  PARENT_ID INT(10) NOT NULL,
  OPERATOR_ID BIGINT NOT NULL,
  BACK_COLOR INT(10) DEFAULT 0,
  PRIMARY KEY (ID)
);


-- 主机cpu内存使用趋势表
CREATE TABLE TBL_HOST_CPU_MEM_TREND (
  ID BIGINT unsigned NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  TIME BIGINT NOT NULL ,
  CPU_RATE double,
  MEMORY_RATE double,
  FLOW_STAT double DEFAULT 0,
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  HOST_POOL_ID BIGINT,
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);


-- 存储资源使用趋势表
CREATE TABLE TBL_STORAGE_TREND (
  ID BIGINT unsigned NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  STORAGE_KEY VARCHAR(64) COMMENT '存储资源的唯一标示符' ,
  TIME VARCHAR(24) NOT NULL,
  ALLOCATION double,
  TOTAL double,
  USE_RATE double,
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

-- 组织资源配额审计表
CREATE TABLE TBL_ORG_AUDIT_STAT (
  ID BIGINT unsigned NOT NULL AUTO_INCREMENT,
  ORG_ID BIGINT COMMENT '组织ID',
  NAME VARCHAR(256) NOT NULL,
  DESCRIPTION VARCHAR(256),  
  TIME varchar(24) NOT NULL,
  MAX_VM_NUM int(10), 
  ALLOT_VM_NUM int(10),
  VM_NUM_RATE double,
  MAX_CPU_NUM int(10) COMMENT 'CPU最大限制',
  ALLOT_CPU_NUM int(10) COMMENT 'CPU分配',
  CPU_NUM_RATE double COMMENT 'CPU分配比例',
  MAX_MEM_NUM int(10) COMMENT '内存最大限制',
  ALLOT_MEM_NUM int(10) COMMENT '内存分配',
  MEM_NUM_RATE double COMMENT '内存分配比例',
  MAX_STORAGE_NUM int(10) COMMENT '存储最大限制',
  ALLOT_STORAGE_NUM int(10) COMMENT '存储分配',
  STORAGE_NUM_RATE double COMMENT '存储分配比例',
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);

-- VMWARE主机性能采集表
CREATE TABLE TBL_VCHOST_PREF_DETAIL (
  ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  TIME BIGINT NOT NULL DEFAULT 0,
  CPU_RATE double,
  MEMORY_RATE double,
  IO double,
  NET double,
  HOST_KEY VARCHAR(64),  
  CLUSTER_KEY VARCHAR(64),
  OP_GROUP_ID BIGINT DEFAULT 1,
  OP_GROUP_CODE VARCHAR(256) DEFAULT '00',
  PRIMARY KEY (ID)
);
-- VMWARE主机性能采集报表
CREATE TABLE TBL_VCHOST_PREF_HOUR_STAT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型', 
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  TIME varchar(24) NOT NULL,
  MEMORY double(10,2) unsigned DEFAULT NULL,
  CPU double(10,2) unsigned DEFAULT NULL,  
  MEMORY_MAX double(10,2),
  MEMORY_MIN double(10,2),
  CPU_MAX double(10,2),
  CPU_MIN double(10,2),
  IO double,
  NET double,
  IO_MAX double,
  NET_MAX double,
  IO_MIN double,
  NET_MIN double,
  PRIMARY KEY (ID)
);

-- 自定义监控表
CREATE TABLE TBL_DEFINED_PAGEINFO (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  COL INT(10) NOT NULL,
  ROW INT(10) NOT NULL,
  SIZE_X INT(10) NOT NULL,
  SIZE_Y INT(10) NOT NULL,
  DATA_ID VARCHAR(256) NOT NULL,
  DATA_TITLE VARCHAR(256),
  DATA_ITEM VARCHAR(256),
  DATA_RELATIVE LONGTEXT,
  DATA_DISK VARCHAR(256),  
  OPERATOR_ID BIGINT,
  NODE_ID BIGINT,
  DATA_GRAPH int(10) DEFAULT 0,
  PRIMARY KEY (ID)
);

-- 虚拟机明细表 CIC
CREATE TABLE TBL_DOMAIN_DETAIL (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CLOUD_ID BIGINT COMMENT '云资源id',   
  CLOUD_TYPE INT COMMENT '云资源类型',
  VM_KEY VARCHAR(64) COMMENT '虚拟机的唯一标示符',
  HOST_KEY VARCHAR(64) COMMENT '主机的唯一标示符',
  CLUSTER_KEY VARCHAR(64) COMMENT '集群资源的唯一标示符',
  NAME varchar(128) DEFAULT '',
  TITLE varchar(128) DEFAULT '',
  MEMORY int(10) unsigned  DEFAULT '0' COMMENT '内存，兆',
  CPU int(10) unsigned  DEFAULT '0' COMMENT 'CPU个数',
  STORAGE_CAPACITY int(10) DEFAULT '0',
  START_TIME DATETIME,
  END_TIME DATETIME,
  UPTIME BIGINT DEFAULT -1 COMMENT '虚拟机运行时间',
  PRIMARY KEY (ID)
);

-- CIC插件表
CREATE TABLE TBL_PLUGIN (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(10) NOT NULL COMMENT '名称，英文+数字，用于url路径',
  TITLE VARCHAR(45) NULL COMMENT '中英文数字，用于界面显示',
  DESCRIPTION VARCHAR(256) NULL COMMENT '任意字符，对该插件的描述',
  LOCATION VARCHAR(256) NOT NULL COMMENT '插件包上传的位置',
  VERSION VARCHAR(45) NOT NULL DEFAULT '1.0' COMMENT '版本',
  ENABLE INT(2) NOT NULL DEFAULT 0 COMMENT '是否启用，0不启用 1启用',
  PRIMARY KEY (ID)
);

-- CIC云彩虹数据中心位置信息
CREATE TABLE TBL_RAINBOW_DEFINED_ITEM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TARGET_ID BIGINT COMMENT '目标节点ID',
  LOCATION_X double DEFAULT NULL,
  LOCATION_Y double DEFAULT NULL,
  TYPE int(10) COMMENT '节点类型   0.云资源  1.主机池  2.集群  3.主机',
  PUBLIC_CLOUD_ID BIGINT,
  PRIMARY KEY (ID)
);
CREATE TABLE TBL_CERTI_CRL (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	SERIAL_NUMBER varchar(128) NOT NULL COMMENT '证书序列号',
	REVOCATION_TIME DATETIME NOT NULL COMMENT '吊销日期',
	INSERT_TIME DATETIME NOT NULL COMMENT '插入日期',
	PRIMARY KEY (ID)
);

CREATE INDEX DOMAIN_DETAIL_HOST_ID_INDEX ON TBL_DOMAIN_CPU_DETAIL (`TIME`,`HOST_ID`, `OP_GROUP_CODE`);
CREATE INDEX DOMAIN_DETAIL_HOST_POOL_ID_INDEX ON TBL_DOMAIN_CPU_DETAIL (`TIME`,`HOST_POOL_ID`, `OP_GROUP_CODE`);
CREATE INDEX DOMAIN_DETAIL_CLUSTER_ID_INDEX ON TBL_DOMAIN_CPU_DETAIL (`TIME`,`CLUSTER_ID`, `OP_GROUP_CODE`);

CREATE INDEX HOST_DETAIL_HOST_POOL_ID_INDEX ON TBL_HOST_CPU_MEM_DETAIL (`TIME`,`HOST_POOL_ID`, `OP_GROUP_CODE`);
CREATE INDEX HOST_DETAIL_CLUSTER_ID_INDEX ON TBL_HOST_CPU_MEM_DETAIL (`TIME`,`CLUSTER_ID`, `OP_GROUP_CODE`);

CREATE INDEX VSWITCH_PORT_FLOW_Index_2 ON TBL_VSWITCH_PORT_FLOW (`DOMAIN_ID`,`TIME`);

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;


