#!/bin/bash
###############################################################################
#    Func Name: crm
# Date Created: 2018-01-11
#       Author: luofangli 
#  Description: crm status
#        usage: $0 $1 
#               $1 : status; must
#       Output: None
#       Return: 0  : success
#               1  : failed
#      Caution: 
#-----------------------------------------------------------------------------
#  Modification History 
#  DATE        NAME             DESCRIPTION
##############################################################################
###############################################################################
## Initialization shell
###############################################################################

main()
{
    if [ $# -lt 1 ] ; then
        usage
        exit 1
    fi
    
    type=$1
    if [ "X$type" = "Xstatus" ]; then
        /usr/sbin/cmsadm status 2>/dev/null
        if [ $? != 0 ]; then
            exit 1
        fi
    else
        echo "ERROR: $0 $type"
        echo "usage: $0 status"
        exit 1
    fi
    exit 0
}
main $@


