ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE Nullable(Decimal128(2))  DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE Nullable(Decimal128(2)) DEFAULT NULL;

ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS HUGEPAGE_MEMORY_TOTAL Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS HUGEPAGE_STATUS Nullable(UInt32) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS OVS_ISOLATED_MEM Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS VM_ISOLATED_MEM Nullable(Decimal128(2)) DEFAULT NULL;
ALTER TABLE metrics.TBL_HOST_CPU_MEM_DETAIL ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL Nullable(Decimal128(2)) DEFAULT NULL;


ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_5M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));


ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_30M ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));



ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1H ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS VM_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS OVS_GROUP_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS HUGEPAGE_MEMORY_TOTAL_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_HOST_CPU_MEM_DETAIL_1D ADD COLUMN IF NOT EXISTS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));


ALTER TABLE metrics.TBL_DOMAIN_CPU_DETAIL ADD COLUMN IF NOT EXISTS CPU_READY Nullable(Decimal128(2)) DEFAULT NULL;

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_5M ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_30M ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1H ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_MAX AggregateFunction(MAX, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_MIN AggregateFunction(MIN, Nullable(Decimal128(2)));
ALTER TABLE metrics.AGG_DOMAIN_CPU_DETAIL_1D ADD COLUMN IF NOT EXISTS CPU_READY_AVG AggregateFunction(AVG, Nullable(Decimal128(2)));

ALTER TABLE metrics.TBL_VSWITCH_FLOW ADD COLUMN IF NOT EXISTS BANDWIDTH Nullable(Decimal128(2)) DEFAULT NULL;


DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_5M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_30M;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1H;
DROP VIEW IF EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1D;


CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_5M
TO metrics.AGG_HOST_CPU_MEM_DETAIL_5M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 5  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_30M
TO metrics.AGG_HOST_CPU_MEM_DETAIL_30M
AS SELECT
              toStartOfInterval (TIME, INTERVAL 30  minute) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1H
TO metrics.AGG_HOST_CPU_MEM_DETAIL_1H
AS SELECT
              toStartOfHour(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE MATERIALIZED VIEW IF NOT EXISTS metrics.VIEW_HOST_CPU_MEM_DETAIL_1D
TO metrics.AGG_HOST_CPU_MEM_DETAIL_1D
AS SELECT
              toStartOfDay(TIME) as TIME,
      HOST_POOL_ID,
      CLUSTER_ID,
      HOST_ID,
      any(OP_GROUP_ID) AS OP_GROUP_ID,
      any(OP_GROUP_CODE) AS OP_GROUP_CODE,
      maxState(CPU_RATE) AS CPU_RATE_MAX,
      minState(CPU_RATE) AS CPU_RATE_MIN,
      avgState(CPU_RATE) AS CPU_RATE_AVG,
      maxState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MAX,
      minState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_MIN,
      avgState(CPU_USAGE_MHZ) AS CPU_USAGE_MHZ_AVG,
      maxState(MEMORY_RATE) AS MEMORY_RATE_MAX,
      minState(MEMORY_RATE) AS MEMORY_RATE_MIN,
      avgState(MEMORY_RATE) AS MEMORY_RATE_AVG,
      maxState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MAX,
      minState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_MIN,
      avgState(HUGEPAGE_MEM_RATE) AS HUGEPAGE_MEM_RATE_AVG,
      avgState(HUGEPAGE_MEMORY_TOTAL) AS HUGEPAGE_MEMORY_TOTAL_AVG,
      avgState(FLEXIBLE_HUGEPAGE_MEMORY_TOTAL) AS FLEXIBLE_HUGEPAGE_MEMORY_TOTAL_AVG,
      maxState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MAX,
      minState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_MIN,
      avgState(FLEXIBLE_HUGEPAGE_MEM_RATE) AS FLEXIBLE_HUGEPAGE_MEM_RATE_AVG,
      maxState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MAX,
      minState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_MIN,
      avgState(VM_GROUP_MEM_RATE) AS VM_GROUP_MEM_RATE_AVG,
      maxState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MAX,
      minState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_MIN,
      avgState(OVS_GROUP_MEM_RATE) AS OVS_GROUP_MEM_RATE_AVG,
      maxState(BUFFER_RATE) AS BUFFER_RATE_MAX,
      minState(BUFFER_RATE) AS BUFFER_RATE_MIN,
      avgState(BUFFER_RATE) AS BUFFER_RATE_AVG,
      maxState(CACHED_RATE) AS CACHED_RATE_MAX,
      minState(CACHED_RATE) AS CACHED_RATE_MIN,
      avgState(CACHED_RATE) AS CACHED_RATE_AVG,
      maxState(SWAP_RATE) AS SWAP_RATE_MAX,
      minState(SWAP_RATE) AS SWAP_RATE_MIN,
      avgState(SWAP_RATE) AS SWAP_RATE_AVG,
      maxState(FLOW_STAT) AS FLOW_STAT_MAX,
      minState(FLOW_STAT) AS FLOW_STAT_MIN,
      avgState(FLOW_STAT) AS FLOW_STAT_AVG
   FROM metrics.TBL_HOST_CPU_MEM_DETAIL GROUP BY HOST_POOL_ID, CLUSTER_ID, HOST_ID, TIME;

CREATE TABLE IF NOT EXISTS metrics.TBL_CORE_SERVICE_MON_DATA(
    INSERT_TIME DateTime,
    TIME UInt64,
    SERVICE UInt32,
    METRIC UInt32,
    VALUE Decimal128(2) DEFAULT NULL
    ) ENGINE = MergeTree()
    ORDER BY (TIME)
    TTL INSERT_TIME + INTERVAL 15 DAY;