#!/bin/sh
linux_terminate_process()
{
   sudo killall -9 $1 > /dev/null 2>&1
   return 0
}

set -x

case $1 in 

	remove|purge)

	IfExistUI=`ps awx -o command|awk -F/ '{print $NF}'|grep -x iNodeManager`
	if [ "$IfExistUI" != "" ]
	then
		sleep 5
		linux_terminate_process iNodeManager
	fi

	rm -rf /opt/apps/com.manager.inode.amd
	rm -rf /usr/share/applications/com.manager.inode*.desktop
	rm -rf /usr/share/applications/iNodeManager.desktop
	rm -rf /var/lib/dpkg/info/com.manager.inode.*
	;;
	upgrade)
	;;
	*)
	;;


esac
exit 0