#! /usr/bin/python

import os

try:
    # Python 2.7 or >=3.2
    from sysconfig import get_path

    def _get_purelib():
        return get_path("purelib")
except ImportError:
    from distutils.sysconfig import get_python_lib

    def _get_purelib():
        return get_python_lib(False)

def _unpatch_nova_api():
    dstDir = _get_purelib() + '/nova/api/openstack/compute'
    
    for path in ['/','/plugins/v3','/contrib','/schemas/v3','/schemas','/legacy_v2/contrib']:
        if os.path.exists(dstDir+path):
            if os.path.exists(dstDir+path+'/origin_server_groups.py'):
                os.system("mv %s/origin_server_groups.py %s/server_groups.py" % (dstDir+path,dstDir+path))

def _unpatch_nova_scheduler():
    dstDir = _get_purelib() + '/nova/scheduler'
    
    if os.path.exists(dstDir+'/origin_utils.py'):
        os.system("mv %s/origin_utils.py %s/utils.py" % (dstDir,dstDir))
    
    if os.path.exists(dstDir+'/filters/host_affinity_filter.py'):
        os.system("rm -f %s/filters/host_affinity_filter.py" % dstDir)

def _unpatch_nova_conductor():
    dstDir = _get_purelib() + '/nova/conductor/tasks'
    
    if os.path.exists(dstDir+'/origin_live_migrate.py'):
        os.system("mv %s/origin_live_migrate.py %s/live_migrate.py" % (dstDir,dstDir))

def _unpatch_nova_compute():
    dstDir = _get_purelib() + '/nova/compute'
    
    if os.path.exists(dstDir+'/origin_manager.py'):
        os.system("mv %s/origin_manager.py %s/manager.py" % (dstDir,dstDir))

def _unpatch_nova_objects():
    dstDir = _get_purelib() + '/nova/objects'
    
    if os.path.exists(dstDir+'/origin_numa.py'):
        os.system("mv %s/origin_numa.py %s/numa.py" % (dstDir,dstDir))

def _unpatch_ceilometer_agent():
    dstDir = _get_purelib() + '/ceilometer/agent'
    
    if os.path.exists(dstDir+'/original_base.py'):
        os.system("mv %s/original_base.py %s/base.py" % (dstDir,dstDir))

def _unpatch_ceilometer_compute():
    dstDir = _get_purelib() + '/ceilometer/compute'
    if os.path.exists(dstDir+'/pollsters/custom.py'):
        os.system("rm -f %s/pollsters/custom.py" % dstDir)

def _unpatch_nova():
    _unpatch_nova_api()
    _unpatch_nova_scheduler()
    _unpatch_nova_conductor()
    _unpatch_nova_compute()
    _unpatch_nova_objects()

def _unpatch_ceilometer():
    _unpatch_ceilometer_agent()
    _unpatch_ceilometer_compute()

def _uninstall():
    _unpatch_nova()
    _unpatch_ceilometer()
    
    os.system("rm -rf %s" % (_get_purelib()+'/kilo_cas_patch*'))
    
    os.system("sed -i /openstack-cas-patch-uninstall/d /usr/bin/openstack-cas-uninstall")
    if not os.path.getsize("/usr/bin/openstack-cas-uninstall"):
        os.system("rm -f /usr/bin/openstack-cas-uninstall")
    
    os.system("sed -i /kilo_cas_patch/d /usr/bin/openstack-cas-version")
    if not os.path.getsize("/usr/bin/openstack-cas-version"):
        os.system("rm -f /usr/bin/openstack-cas-version")

    os.system("rm -f %s" % __file__)

if __name__ == "__main__":
    _uninstall()
