#!/bin/sh
# Description: init function

start_daemon () {
        /lib/lsb/openeuler_start_daemon "$@"
}
killproc () {
        /lib/lsb/openeuler_killproc "$@"
}

pidofproc () {
        /lib/lsb/openeuler_pidofproc "$@"
}

log_success_msg (){
        /lib/lsb/openeuler_log_success "$@"
}

log_failure_msg () {
        /lib/lsb/openeuler_log_failure "$@"
}

log_warning_msg () {
        /lib/lsb/openeuler_log_warning "$@"
}
