# H3C CAS CVM ClickHouse Properties
# Original: /etc/cvk/cvm/clickhouse.properties
# Recovered from R0785P03 front.package/clickhouse/clickhouse.properties
# Decrypted: user=default, pass=Pzss@_w0rd

clickhouse.jdbc.driverClassName=com.clickhouse.jdbc.ClickHouseDriver
clickhouse.jdbc.url=jdbc:clickhouse://cas-clickhouse:8123/metrics?rewriteBatchedStatements=true
# Decrypted from xYFZQgBNw0E=: default
clickhouse.jdbc.username=default
# Decrypted from egJU1XOSiZHypdQZAaae9g==: Pzss@_w0rd
clickhouse.jdbc.password=Pzss@_w0rd
