# H3C CAS CVM Kafka Properties
# Original: /etc/cvk/cvm/kafka.properties
# Recovered from R0785P03 front.package/kafka/kafka.properties

bootstrap.servers=cas-kafka:9092
key.serializer=org.apache.kafka.common.serialization.LongSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
producer.type=async
retries=3
acks=all
