# H3C CAS CVM Redis Properties
# Original: /etc/cvk/cvm/redis.properties
# Recovered from R0785P03 front.package/redis/redis.properties
# Decrypted password: Sy@Redi$79

redis.maxIdle=10
redis.minIdle=0
redis.maxTotal=100
redis.maxWaitMillis=100000
redis.testOnBorrow=true
redis.testWhileIdle=true
redis.host=cas-redis
redis.port=6379
# Decrypted from COT723vi0xiIHjhUYAEddg==
redis.password=Sy@Redi$79
redis.database=0
redis.address=redis://cas-redis:6379
