#!/bin/sh

Arch=arm
#停旧服务、备份数据
set -x
linux_terminate_process()
{
   sudo killall -9 $1 > /dev/null 2>&1
   return 0;
}

INSTALL_DIR=/opt/apps/com.manager.inode."$Arch"

case $1 in 

	upgrade)
	
	IfExistUI=`ps awx -o command|awk -F/ '{print $NF}'|grep -x iNodeManager`
	if [ "$IfExistUI" != "" ]
	then
		linux_terminate_process iNodeManager
	fi
	
	#覆盖升级时兼容旧版本的安装包，没有remove|purge这个字段，说明是旧版本安装包；
	#需要屏蔽覆盖安装时，旧deb包postrm脚本会删除升级包安装目录的动作

	POSTRM="/var/lib/dpkg/info/com.manager.inode.${Arch}.postrm"
	TARGET_PATTERN="rm -rf /opt/apps/"

	if ! grep -q 'remove|purge)' "$POSTRM"; then
		sed -i "s|$TARGET_PATTERN|echo |g" "$POSTRM"
	fi
	
	find "$INSTALL_DIR" -mindepth 1 -delete  
	;;
	*)
	;;

esac
exit 0
