blacklist {
    wwid ".*"
}
blacklist_exceptions {
    property "(ID_SCSI|ID_WWN)"
}
defaults {
    path_checker "tur"
    no_path_retry "25"
    path_grouping_policy "group_by_prio"
    prio "const"
    max_fds "max"
    failback "immediate"
    san_path_err_recovery_time 90
    san_path_err_threshold 3
    san_path_err_forget_rate 18
}

