#!/bin/bash 
LOG_DIR="/var/log/res_monitor"
LOG_ABORTED="$LOG_DIR/log_aborted.log"
LAST_PROC_OUTPUT="$LOG_DIR/.last_proc_output"
LAST_SUBCMD_OUTPUT="$LOG_DIR/.last_subcmd_output"


# thresold that will trigger recording or not
# if disk available space is less than 2048M, then will not record log
MIN_SPACE_REQUIRED_FOR_LOG=2048
# this is a placeholder for disk currently
DISK_WARNING_THRESOLD=90
# if memory`s usage is greater than or equal 90%, then will log process
MEMORY_WARNING_THRESOLD=90
# if cpu`s usage is greater than or equal 90%, then will log process
CPU_WARNING_THRESOLD=90

# tools needed
#TOOLS_FINCORE="/usr/sbin/linux-fincore -s"
TOOLS_FINCORE="/usr/sbin/vmtouch -v"
